### ISSUE TITLE
User is unable to publish updates to dshop

### ISSUE THREAD

**Issue by christopherchelpka** [OriginProtocol/dshop#1000]
I am unable to publish updates for https://della-chelpka-art.ogn.app. When I click PUBLISH, all I get is a spinning blue circle in one browser (Brave) and a frozen blue in another (Safari).

**Comment by phyninja** [comment]
Hi @christopherchelpka,

Sorry about the late response to this post. If you haven't already received emails about DShop admins needing to take steps to migrate their shops away from the *.ogn.app domain, please take a look at the attached pdf.
[Dshop_Migration.pdf](https://github.com/OriginProtocol/dshop/files/7474528/Mail_-_Dshop_Migration.pdf)

Links:
- "[new chapter](https://blog.originprotocol.com/a-new-chapter-for-dshop-giving-control-to-the-community-12e8ec7ee5ca)": 
- "[(AWS) documentation on GitHub](https://github.com/OriginProtocol/dshop/blob/master/docs/dshop/deployment/aws.md)"
- "[(GCP) documentation on GitHub](https://github.com/OriginProtocol/dshop/blob/master/docs/dshop/deployment/gcp.md)"
- "[developers documentation on GitHub](https://github.com/OriginProtocol/dshop)"
- "[support articles](https://help.originprotocol.com/hc/en-us/categories/360004346733-Dshop )"

**Comment by phyninja** [comment]
@christopherchelpka 
Apart from opening an issue in this repository, I invite you to contact the DShop community [on Discord](https://discord.gg/ogn) if you face issues with your shop. 

Sincerely,
Rajath
