### ISSUE TITLE
Customer is unable to complete transaction

### ISSUE THREAD

**Issue by christopherchelpka** [OriginProtocol/dshop#1001]
Problem: A customer notified me that they were unable to advance beyond the first step of the checkout process (entering email) and was therefore unable to complete and order. This was on a mobile device. I tried it and faced the same problem. This is for https://della-chelpka-art.ogn.app

Related Question: How can I know the checkout process is broken besides customer feedback?

**Comment by phyninja** [comment]
#955 addressed the documented issue.
