### ISSUE TITLE
I have a problem placing the order .. ERROR ( Access to XMLHttpRequest at 'https://fs.ogn.app/api/v0/add' from origin has been blocked by CORS policy )

### ISSUE THREAD

**Issue by CRPTcuan** [OriginProtocol/dshop#1007]
Hi .. I am trying to implement origin dshop and I would like to know if you can help me with this problem .. I have a problem placing the order. ,, the sale .. neither with cryptographic payment nor manual methods they manage to close the sale. Attached screenshot of the error in chrome and brave. Let's see if you can help me please ... thank you very much .. sorry for my bad English .. I am using a translator .. Thank you

brave error
![brave copy](https://user-images.githubusercontent.com/86898526/139290718-e5113ac8-cfb3-42fa-9256-2b62d062ad49.png)

chrome error
![chrome copy](https://user-images.githubusercontent.com/86898526/139290737-00b687bc-b897-439a-a850-a04c8169a23d.png)

**Comment by phyninja** [comment]
@CRPTcuan What is the status of this issue? 

My last response is below, for reference:
> From [this blog](https://www.stackhawk.com/blog/fixing-no-access-control-allow-origin-header-present/) , I learned some of the technical details behind the error `No 'Access-Control-Allow-Origin' header is present on the requested resource`. According to the author, modern-day web browsers will first ask the "requested resource" whether it has any policies with respect to requests it will tend to before submitting the same to the resource. In our case, a conversation between the browser and the IPFS API server may go like this:
> 
> *You make a "request" to add some data to the IPFS API server by clicking on the 'Pay' button*
> **Browser**: Hey, I have a request to make, but first, can you tell me if you have any conditions regarding whom you will accept requests from? 
> **IPFS API Server**:  Yes, I will only accept requests coming from the same domain as me (ogn.app). 
> 
> The browser will then study your request to check whether it meets the server's policy. If it doesn't, it will revert back to you with the error above before even submitting the [payment] information to the server. It is for this reason that the Gateway server exists. A Gateway server is named as such because it acts as **gate** between the external world and the server that it houses. Notice how the IPFS Gateway has the same domain as the IPFS API server; to me, this says that IPFS API will accept requests coming from the Gateway server. 
> 
> Lately, people have been experiencing [issues with the IPFS Gateway server](https://discord.com/channels/404673842007506945/809309667398385694/903467814898266175) `https://fs-autossl.ogn.app`. I therefore recommend that you change the IPFS Gateway and API to a different domain (Ex. [Infura](https://infura.io/docs/ipfs)), publish your DShop, and then restart your GCP instance. Your Networks page will take on these changes if you choose to go with Infura:
> `IPFS Gateway`: https://ipfs.infura.io/
> `IPFS Server`: https://ipfs.infura.io:5001/

**Comment by CRPTcuan** [comment]
Hi .. if I had responded in the other thread .. it worked perfect ,, thank you very much that was it .. and I made an account in infura because they give 5 gigs for ipfs

thank you :)
