### ISSUE TITLE
Unable to publish changes - DShop IPFS

### ISSUE THREAD

**Issue by phyninja** [OriginProtocol/dshop#1014]
> I would like to know if you can help me with this problem .. I can't publish the changes to make the shop publicly visible, it always show me this message.
![Screenshot from 2021-11-19 02-54-59](https://user-images.githubusercontent.com/53530531/142551847-9fa569f7-a6f5-407d-bae7-5ab49f5e47d9.png)

_Originally posted by @GhassenMedyouni in https://github.com/OriginProtocol/dshop/issues/1005#issuecomment-973657485_

**Comment by GhassenMedyouni** [comment]
@phyninja I create my marketplace Dshop, I can't make it public, this is my Network config [
![Screenshot from 2021-11-24 00-37-41](https://user-images.githubusercontent.com/53530531/143146963-974ab21f-9c79-42d8-9658-c58459068acd.jpg)
![Screenshot from 2021-11-24 00-37-41](https://user-images.githubusercontent.com/53530531/143146981-251a67b3-da51-458f-b41e-1efdf622c675.png)
](url)

the public URL still inaccessible
![Screenshot from 2021-11-24 00-54-55](https://user-images.githubusercontent.com/53530531/143147268-2ad0bf42-e6ba-498a-a410-62640160a842.jpg)

**Comment by kellyalb** [comment]
Hi,

could you try creating a free Piñata account and connect it via key/secret?

**Comment by phyninja** [comment]
@GhassenMedyouni, I stand by @kellyalb's message above.

**Comment by GhassenMedyouni** [comment]
@kellyalb I create a Pinata account , but still the same issue 
![pic1](https://user-images.githubusercontent.com/53530531/143329761-197e30aa-4bff-49cd-b71c-4303f6236306.jpg)
after i click publish nothing has been chnaging 
![pic2](https://user-images.githubusercontent.com/53530531/143329851-a9a7fcb5-c3a7-4720-a889-9c05b6d8f7ab.jpg)

**Comment by kellyalb** [comment]
Hmmm… in your first screenshot, I’d the box for “Piñata pinning” check down below?

what happens if you try to deploy from the Super Admin > Shops > [your shop] > Deploy section?

**Comment by GhassenMedyouni** [comment]
the deployment is worked , but i can't activate it.

**Comment by GhassenMedyouni** [comment]
@kellyalb i appreciate your help, thnks..

**Comment by GhassenMedyouni** [comment]
@kellyalb the deployment was worked, but i can't activate it.
![pic1](https://user-images.githubusercontent.com/53530531/143343116-71fe9ea2-d63a-4c05-8caa-2ad5934b1d89.jpg)
![pic2](https://user-images.githubusercontent.com/53530531/143343692-09a43087-7be6-4c50-9476-4c121a4674fd.jpg)

**Comment by kellyalb** [comment]
That seems like progress. Activate doesn’t work for me either. I’m guessing now it may be up to how you are configuring your DNS. Do you feel confident in that part?

**Comment by GhassenMedyouni** [comment]
@kellyalb are you know how to configure the Dns ??

**Comment by GhassenMedyouni** [comment]
@kellyalb Do you know how to configure the DNS?

**Comment by GhassenMedyouni** [comment]
@kellyalb i  think the problem is that there is no a DNS provider but how to add it. ??
![1](https://user-images.githubusercontent.com/53530531/143522476-a2ed8899-7226-4d33-bd12-78cf57a57934.jpg)

**Comment by phyninja** [comment]
Hello,
To gain insight into why the 'Activate' button doesn't work, I looked into the source code for DShop. Like myself, you may also find the following error message displayed on your web browser's **console** when you click on the button:
`Error setting hostname: 400: Bad Request`

The error arises because the app expects a value in the `DNS Provider` field here:
![image](https://user-images.githubusercontent.com/10854442/143565953-28c1579e-b6ca-4dda-a44c-ae00f731adf5.png)

@kellyalb would you please continue providing support?

**Comment by kellyalb** [comment]
I wasn’t able to get the DNS Provider functionality working in Dshop. I had to get Dshop working by manually configuring my DNS settings for my domain starting at its registrar. I’d need to double check the exact configuration that worked for me, but I believe it was a combination of A records and wild card sub domains. 

@GhassenMedyouni do you have your Root Domain pointing to the IP address of the server where Dshop is installed? Then do you also point to the same IP address for all subdomains, by using a * for a wildcard, for that Root domain?

**Comment by GhassenMedyouni** [comment]
@kellyalb i create a new record with the public URL and point to the same address IP.
![11111](https://user-images.githubusercontent.com/53530531/143918116-8fb9e0d9-8969-4bd7-9a6a-fafe70adb24a.jpg)
i want to have the access to the shop like a simple user 
![12222222](https://user-images.githubusercontent.com/53530531/143918343-ce141c3b-23d1-4e5d-bb89-99927f6cd9c9.jpg)

**Comment by GhassenMedyouni** [comment]
> 

@kellyalb Hi again,  I am stuck in the same step, the DNS provider always displays none, so I cannot activate the shop even though I have created new records for the subdomain with the same IP address. Thank you for your help until now.

**Comment by phyninja** [comment]
What is the result of using the route below?
1) Go to Settings > General from the DShop Admin console
2) Click on the **Add a custom domain** button and enter details
![Add a custom domain](https://user-images.githubusercontent.com/10854442/145383297-0a293b6e-5382-4979-9565-c515ffa625b0.png)
3) Update DNS records on the Domain registrar's side as directed

**Comment by GhassenMedyouni** [comment]
@phyninja I added a custom domain also i created a new record with the custom domain and i pointed to the same IP address.
![pic1_dns](https://user-images.githubusercontent.com/53530531/145564451-6a85320b-d915-4a12-bb67-2d8eab7311c9.jpg)

**Comment by phyninja** [comment]
@GhassenMedyouni

On Origin's Discord Server, there are some messages posted by users who also had trouble configuring DNS settings for DShop. I looked through them, but can't say that I found something that might help. 

They say, however, that "DNS propagation may take up to 48 hours (to propagate)". Since it has been longer than that since we last talked, could you check back in at your convenience and provide us an update?

**Comment by phyninja** [comment]
@GhassenMedyouni, you said previously that "the DNS provider always displays none, so (you) cannot activate the shop even though (you) have created new records for the subdomain with the same IP address." 

Since @kellyalb mentioned the workaround of configuring DNS settings from the Domain registrar's side, we should continue pursuing that route to fix this issue. What is the name of the Domain registrar you're using?

**Comment by GhassenMedyouni** [comment]
@phyninja, The domain name that I'm using is turnip. Ovh hosted in route 53 Amazon.

**Comment by phyninja** [comment]
>  turnip.ovh
We need to take a moment to check the spelling. Can you confirm that it's **turnip**, not **tunip**?

**Comment by GhassenMedyouni** [comment]
> > turnip.ovh
> 
> We need to take a moment to check the spelling. Can you confirm that it's **turnip**, not **tunip**?

@phyninja sorry it's tunip

**Comment by phyninja** [comment]
@GhassenMedyouni I still do not have enough information to help. 
Could you join the Origin Discord Server (https://discord.gg/ogn) and send me a message?
My user name there is **Rajath#0881**; try finding me by entering the user name in the Search Bar on the top-right of the window: 
![Origin Discord](https://user-images.githubusercontent.com/10854442/147736760-ea93b924-f67e-475c-9c90-8426e62b60b8.png)

Discord will allow us to work on this together over a [screen sharing session.](https://support.discord.com/hc/en-us/articles/360040816151-Go-Live-and-Screen-Share#h_01EZK16TZMN11V01BKGKY9JY34).

**Comment by phyninja** [comment]
Over a screen sharing session, @GhassenMedyouni and I worked together to:
- Launch a new EC2 instance from the DShop AMI
- Add ['Custom Domain' records](https://github.com/OriginProtocol/dshop/blob/master/docs/dshop/deployment/aws.md#custom-domain) on the Route 53 interface, and 
- Configure the [DShop Deployer](https://github.com/OriginProtocol/dshop/blob/master/docs/dshop/deployment/first-run.md).

I then 
- created a new shop
- added a custom domain from Settings > General
- made (recommended) changes on the domain-registrar end, and 
- attempted to publish the store. 

The URL shown in the **Host** filed of the CNAME record directs a user to the DShop Admin console. The URL that the public can access the shop is to be determined.

**Comment by phyninja** [comment]
@GhassenMedyouni,

I found the place in our codebase that displays the error "Something went wrong. Try again later" (Ref: https://github.com/OriginProtocol/dshop/issues/1014#issuecomment-990876073), but not the answer to the question of how the public can access your shop.

Could you help me by taking the following steps, and posting the result?
1) Start the DShop Instance
2) Go to the DShop Admin console > Settings > General
3) Copy the URL under 'Domain Name'
4) Open a new Private window in your web browser  OR open a window in a different web browser
5) Navigate to the URL.

**Comment by phyninja** [comment]
We found that adding the following two DNS records allowed for @GhassenMedyouni's shop to 'go live' on a public URL:

| Record Type | Record name | Host/Value |
| -------- | ------ | ----- |
| A | `Backend Public URL` | `IP address of the EC2 instance` |
| A | *.tunip.ovh | `IP address of the EC2 instance` |


Credits:
https://github.com/OriginProtocol/dshop/issues/1014#issuecomment-980062027
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html#domain-name-format-asterisk
