### ISSUE TITLE
External deployer: Preview and publish changes

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#103]
Whenever a user makes any new changes to their shop (e.g) adding a new product or collection, they should be prompted to publish their changes (deploy to IPFS) in order for the changes to be publicly visible.

**To publish changes**

A yellow bar will be persistent across pages ([see on Zeplin](https://zpl.io/beqnLwB)), reminding them that they have changes that have not been published.
- [ ] Clicking "publish changes" will begin deploying the changes to IPFS
- [ ] After clicking publish, the user [will see this state ](https://zpl.io/VxzkLmx)while the changes are being published
- [ ] [This final screen](https://zpl.io/bWoKk47) shows the user that the changes are now published and live

If this is the first time the user is deploying his store to IPFS, upon clicking "publish changes",
- [ ] He will be [prompted to connect a web3 wallet](https://zpl.io/blqrZ7k). 
- [ ] He will then [see this](https://zpl.io/awRykJn) when his wallet has been connected. If he doesn't connect a wallet and dismisses the modal, he will continue to see the persistent yellow bar asking him to publish changes.

**To preview changes**

[The persistent yellow bar](https://zpl.io/beqnLwB) prompting users to publish their changes will also have a "preview" button. Clicking this button will simply launch a new tab showing the user what their shop looks like with the latest changes (but not yet deployed to IPFS).

**Comment by franckc** [comment]
In addition to publishing the changes on IPFS, we should also call the marketplace contract "updateListing" to emit a ListingUpdated event. This will make the dshop data public and also trigger a re-indexing of the data by the BigQuery ETL pipeline.

**Comment by franckc** [comment]
@nick @shahthepro I won't be able to follow up on this task this week. Any chance one of you may be able to handle it? I think @nick you said that this was already mostly done... Thanks! :)

**Comment by shahthepro** [comment]
@franckc Have a few things on my list. Can pick this up once they are done. 

>  think @nick you said that this was already mostly done
Yes, I think, I have seen the UI but it is not yet wired up.
