### ISSUE TITLE
Listener fails getting block

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#107]
A user that uses infura reported hitting the following error on the listener:
```can't read property timestamp of null```
The stack trace points to this line: https://github.com/OriginProtocol/dshop/blob/master/backend/utils/events.js#L53

He is using Infura. So I bet what's happening is:
 - listener gets notified of a new event
 - listener tries to read the associated block but due to Infura inconsistencies, fetching the block fails.

It won't be an issue on our infra, but could show up on other user's deployment if they use Infura.

We could potentially harden the listener by implementing a retry?

@mikeshultz Any thoughts?

**Comment by mikeshultz** [comment]
I added a best-effort bypass that uses current UTC timestamp when that fails.  Probably okay, but maybe we can add retries to that getBlock request to lower the error rate.

relevant changes will be in PR #113

**Comment by mikeshultz** [comment]
Going to close this.  If we have other issues come up we can create a new issue.
