### ISSUE TITLE
Add a way to finalize crypto offers so that funds get released to the seller

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#114]
Currently when a buyer pays in crypto, the funds stay in the marketplace escrow and don't get released to the seller.

There is a workaround which is for the seller to go to shoporigin.com and finalize the offer but it is clunky.

We should add a way for
 1. the seller to finalize the offer from the dshop admin after the escrow deadline expires so that the funds get released to the seller wallet
 2. the buyer to release the funds after receiving the good or to file a dispute

Item 1. is definitely higher priority than 2.

**Comment by franckc** [comment]
CC @gullible1 @nick 

Note: this was requested by one of our early dshop adopter in discord.

**Comment by nick** [comment]
This is done now
