### ISSUE TITLE
IPFS ingress with wildcard for *.ogn.app

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#117]
For the sake of speed of launching dapps on `*.ogn.app` look into setting up a wildcard cert for use on an IPFS gateway ingress.  This would ease the pain for "first launch" when users are trying out their store.

Ref: #115

**Comment by mikeshultz** [comment]
Currently many(most/all?) other domains are CNAMEd directly to this.  For this to work, it must go through the current IPFS issuer ingress or autossl will no longer work.  So this will need to be implemented within OpenResty.

**Comment by mikeshultz** [comment]
We found ourselves in a pretty unique edge case.

[lua-resty-auto-ssl doesn't currently support wildcards](https://github.com/auto-ssl/lua-resty-auto-ssl/issues/97).  As noted in that issue, one solution is to generate the cert manually and use it as the fallback certificate(we use a self-signed one right now).  I think this may be our only solution that doesn't involve potentially weeks of work.

Another option would be to modify `lua-resty-auto-ssl` to support wildcard certs.  I'd bet this would take a couple of weeks.  Unfamiliar codebase and I've barely touched lua before.

I was looking into other ways to automate the fallback cert but none of that was really working.  Was looking at maybe using [`dnsrobocert`](https://dnsrobocert.readthedocs.io/en/latest/index.html) to generate the wildcard, then using a custom hook script to upload to an s3-like bucket.  Then the issuer container could download the cert on start.  However, there's no good way to have the expiration detected, security concerns abound, and we probably shouldn't just knock over the ipfs-issuer every night to download the latest cert causing service interruptions.

Another option would be to scratch the requirement that users must be able to CNAME their `whatever.ogn.app` domain.  Setting up an ingress with a wildcard cert alone is pretty easy.  Setting one up that has a wildcard cert and an auto-issuer together is the challenge. 

Right now the best solution for the original requirements are to either human-automate this process with calendar alerts(every ~90 days run X command), or to just kick the can down the road to where the 15-60sec wait time the user has to wait for their `whatever.ogn.app` cert to generate becomes a big deal we need to tackle.  Perhaps down the road `lua-resty-auto-ssl` might add wildcard support as well, which would be ideal.

For now I'm inclined to work on something else for the time being because I've been burning a lot of time on this. Thoughts, anyone? @franckc @nick

**Comment by franckc** [comment]
Thanks for writing this down.

IMHO, given that implementing a fully-automated solution would take a significant amount of engineering, I think it for now running that command manually every 90 days is not that bad. Perhaps we document the exact steps for that command in the  playbook and then we set a recurring reminder to run it every 90 days in the calendar?

**Comment by franckc** [comment]
@mikeshultz Doing some dashboard cleanup. Ok if I move this back to the backlog since we are not actively working on it right now? https://github.com/orgs/OriginProtocol/projects/3

**Comment by mikeshultz** [comment]
I guess

**Comment by mikeshultz** [comment]
Due to recent deployment/infra changes, closing this in favor of #695
