### ISSUE TITLE
Additional Settings screen fields

### ISSUE THREAD

**Issue by nick** [OriginProtocol/dshop#119]
Ability to configure the following fields in `config.json`:

* Notice
* Byline
* Meta Description
* Cart Summary Note
* Email Subject
* Support Email Address
* Custom CSS
* Discount Codes

Details:

`"notice": ""`

Results in a notice at the top of the screen, eg:

![image](https://user-images.githubusercontent.com/939/85434718-b4dc6380-b543-11ea-9f69-2759b92e20f2.png)

`"byline": ""`

The string that appears to the right of the logo. See image above.

`"metaDescription": ""`

For SEO. Appears in HTML.

`"cartSummaryNote": ""`

Text appears under summary in checkout process:

![image](https://user-images.githubusercontent.com/939/85434950-04bb2a80-b544-11ea-9c57-c16a54bc0a50.png)

`"emailSubject": ""`

The email subject for receipt emails

`"supportEmail": "My Store <my-store@ogn.app>"`

Self explanatory.

`"css": ""` 

Custom CSS.

`"discountCodes": true`

Whether to show the discount code UI on the checkout.

**Comment by nick** [comment]
@rembrandtreyes this could be a great issue for you to tackle once we have some mockups

**Comment by nick** [comment]
Mockups in [Zeplin](https://app.zeplin.io/project/5ec56d4c8f6a762c2368d3e8/screen/5ece92935b536449cd186b17)

**Comment by rembrandtreyes** [comment]
Sweet thanks @nick I will get started on this right away. If I have question I will reach out to the eng channel.

**Comment by rembrandtreyes** [comment]
Hey @nick, am I just adding in the fields and styles from the mockups, or am I also adding the keys with default values to `config.json`? Looks like some of these already exist in `config.json`. Also, some of the fields are missing from the mockups in Zeplin.

**Comment by nick** [comment]
Lets just add the fields in the mockup for now
