### ISSUE TITLE
Review TTLs on current domains

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#121]
Review TTLs on current domains.  Make sure they're appropriate.

We may want to include some kind of guidance to users but I'm not currently sure how we tackle this now.  @nick do we currently just send the users an E-mail telling them what to set?

Ref #115

**Comment by nick** [comment]
Hrm I'm not sure which TTL is respected by IPFS... I'm guessing its the one with the actual IPFS hash in it though, so controlled by us.

Ie not sure if it's store.example.com or store.ogn.app assuming store.example.com points to store.ogn.app

**Comment by mikeshultz** [comment]
I assume IPFS is TTL agnostic and just relies on system-level resolution.  But... good point with the CNAME records as I bet that could cause some unexpectedly long record caching.  Worth figuring out so we at least know what to expect.

**Comment by mikeshultz** [comment]
So, for DNS records, if you had a TTL of 1 year on the CNAME but 5 minutes on the TXT, an update to the TXT record should be reflected within 5 minutes.  Changing the CNAME would still take forever if you pointed it somewhere else, but the TTLs should be treated independently.

**Comment by mikeshultz** [comment]
All of the DNSLink records on `ogn.app` seem just fine.  None over 5 minutes.

Perhaps if there are others I'm not aware of, @nick can take care of those.

**Comment by mikeshultz** [comment]
Closing as LGTM
