### ISSUE TITLE
IPNS update speed

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#122]
This is more of a personal task tracker for me to research IPNS and:

1) How it relates to DNSLink
2) How updates are dealt with, including propagation and caching
3) If there's any better alternatives or node-level configuration options that might improve how it works for us

Ref #115

**Comment by mikeshultz** [comment]
General DNSLink resolution:

- checks if dnslink request: https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/hostname.go#L237-L249
- which uses ipfs.Name().Resolve() https://github.com/ipfs/go-ipfs/blob/master/core/coreapi/name.go#L122-L142
- which uses api.Search(ctx, name, opts...) https://github.com/ipfs/go-ipfs/blob/master/core/coreapi/name.go#L84-L118
- which uses namesys.Resolver.ResolveAsync https://github.com/ipfs/go-ipfs/blob/7ce1d751f808d6a990dc496a81f2477742f9e640/namesys/base.go#L42-L113
- which uses resolveOnceAsync https://github.com/ipfs/go-ipfs/blob/7ce1d751f808d6a990dc496a81f2477742f9e640/namesys/dns.go#L49-L120
- which uses workDomain https://github.com/ipfs/go-ipfs/blob/7ce1d751f808d6a990dc496a81f2477742f9e640/namesys/dns.go#L122-L140
- which uses lookupTXT https://golang.org/pkg/net/#LookupTXT

This issue suggests there's a static cache, but I don't see it?  https://github.com/ipfs/go-ipfs/issues/5884

If I'm reading this all correctly, it looks like any DNS record caching is done at system level.

**Comment by mikeshultz** [comment]
IPFS is either the [hash of a pubkey OR DNSLink](https://docs.ipfs.io/concepts/ipns/).  They both fall under the header of "IPNS".  In our case, we're using DNSLink.  If it's a dot separated name it'll be considered DNSLink(e.g. `/ipns/example.ogn.app`) and if it's an IPNS name, it'll be the base58 hash.

**Comment by mikeshultz** [comment]
Publishing an IPNS update:

https://docs.ipfs.io/reference/http/api/#api-v0-name-publish

`lifetime` - Time duration that the record will be valid for. Default `24h`
`ttl` - Time duration this record should be cached for. Uses the same syntax as the lifetime option. (caution: experimental). 

Not really sure why lifetime shouldn't be indefinite?  According to [this discussion topic, it needs to be republished as a keep-alive](https://discuss.ipfs.io/t/ipns-how-much-is-the-lifetime/6705/5).  And [another discussion that suggests the maximum lifetime is `24h`](https://discuss.ipfs.io/t/ipns-max-lifetime/2130/7).

**Comment by mikeshultz** [comment]
IPNS names(non-DNSLink) did not fare as well as DNSLink...

    ipfs key gen mike
    export IPNS_NAME=$(ipfs key list -l | grep mike | awk '{ print $1 }')
    ipfs name publish --resolve=false -k mike --ttl='30s' /ipfs/QmZ4tDuvesekSs4qM5ZBKpXiZGun7S2CYtEZRB3DYXkjGx
    ipfs resolve "/ipns/$IPNS_NAME"
    ipfs name publish --resolve=false -k mike --ttl='30s' /ipfs/QmeeLUVdiSTTKQqhWqsffYDtNvvvcTfJdotkNyi1KDEJtQ

Updating names is super slow for no apparently reason.  This normally took a couple of minutes even with `--resolve=false`.  To boot, this often returned 504s while updating IPNS name. Not for long, but long enough that DNS updates are probably cleaner.

**Comment by franckc** [comment]
Doing some dashboard cleanup. Ok if I move this back to the backlog since we are not actively working on it right now? https://github.com/orgs/OriginProtocol/projects/3

**Comment by mikeshultz** [comment]
this was for personal tracking.  Closing.
