### ISSUE TITLE
Send alert if items in queue fail

### ISSUE THREAD

**Issue by nick** [OriginProtocol/dshop#123]
Right now we don't know if items in the queue fail without manually checking

![image](https://user-images.githubusercontent.com/939/85438571-5ca86000-b549-11ea-8fec-92adf2ffe4c1.png)

**Comment by franckc** [comment]
My plan is to wrap all the queue logic code in a try/catch to will capture an exception via Sentry.
Sentry will send us an email for any new exception.

**Comment by franckc** [comment]
Done for the makeOffer queue.
I still need to wrap some of the other queues, like Printful.

**Comment by franckc** [comment]
@mikeshultz  added a catch-all that will record and exception in Sentry for any queue failure. Closing.
