### ISSUE TITLE
Internal deployer: Add/edit social media links

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#13]
When deploying a store for a merchant, we need to be able to add their social media links and also edit them if needed.

1. I should be able to choose which social media links I want to add (Facebook, Twitter, YouTube, Instagram, Medium)
2. The social media icons should show up below the sidebar on the left, and take me to the respective pages when I click on them
3. I should be able to add/remove social media platforms I want to link to, and also edit the links

**Comment by nick** [comment]
Done by @shahthepro
