### ISSUE TITLE
Internal deployer: basic store setup

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#14]
When deploying a store for a merchant, I need to be able to do the following for them:

- [ ] add a custom domain or use a default dshop domain (if we have one)
- [ ] add/edit store name
- [ ] add/edit store favicon
- [ ] add/edit store logo
- [ ] add/edit the message that goes where it says “100% of all sales…” at the top right hand of the [Stay At Home shop](https://www.stayathomeshop.co/#/)

**Comment by nick** [comment]
Done
