### ISSUE TITLE
Backend crash during deployment

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#147]
Recently saw some crashes on the Rinkeby backend.  This is thrown when the crash occurs:

    E 2020-06-30T18:30:26.620054194Z events.js:174
    E 2020-06-30T18:30:26.620072654Z       throw er; // Unhandled 'error' event
    E 2020-06-30T18:30:26.620092626Z       ^
    E 2020-06-30T18:30:26.620097617Z 
    E 2020-06-30T18:30:26.620101291Z Error: connect ECONNRESET [censored]:443
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
    E 2020-06-30T18:30:26.620109472Z Emitted 'error' event at:
    E 2020-06-30T18:30:26.620113395Z     at TLSSocket.socketErrorListener (_http_client.js:401:9)
    E 2020-06-30T18:30:26.620117215Z     at TLSSocket.emit (events.js:198:13)
    E 2020-06-30T18:30:26.620120814Z     at TLSSocket.EventEmitter.emit (domain.js:448:20)
    E 2020-06-30T18:30:26.620124434Z     at emitErrorNT (internal/streams/destroy.js:91:8)
    E 2020-06-30T18:30:26.620128059Z     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    E 2020-06-30T18:30:26.620131969Z     at process._tickCallback (internal/process/next_tick.js:63:19)

Aure was testing out updating his products for his store and this seems to occur during or after deployment. "add prod > save > deploy > view storefront > explosion"

EDIT: The cencored IP goes to the IPFS issuer("IPFS Gateway" in settings)

**Comment by mikeshultz** [comment]
This appears to happen while priming IPFS.  This is immediately (7ms) before the error:

    [INFO] dshop.utils.primeIpfs: Priming https://ipfs-prod.ogn.app/ipfs/QmafcS7cQRsjf5Tx4LXu16yajE4b4NVisECpbhzwjircTr/images/master.svg

**Comment by nick** [comment]
It could be that the order of 'priming' is important here. Originally it was set to 'prime' in the following order:

gateway.pinata.cloud
gateway.ipfs.io
ipfs-prod.ogn.app

**Comment by mikeshultz** [comment]
Could be, but it's only one file of the folder.  Inclined to consider it an occasional network hiccup.  I added an error handler to the bottleneck scheduler to at least prevent a crash from happening and the process should continue on.  Will keep an eye on this and see how often it occurs.

**Comment by mikeshultz** [comment]
Okay, after a few attempts this error event is properly handled now.

The issue may be related to my pinata account getting full.  Will be cleaning that up tomorrow.  Will keep an eye on this over the next few days.

**Comment by franckc** [comment]
@mikeshultz Doing some dashboard cleanup. Do we need to keep this open or can we close it?

**Comment by mikeshultz** [comment]
Leave this open for now.

**Comment by mikeshultz** [comment]
Just realzied what this was.  Solved.

Related: #163
