### ISSUE TITLE
IPFS Priming of configured gateway failed

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#167]
Priming for the configured IFPS gateway doesn't happen.  Appears it's checking the wrong config var name here:

https://github.com/OriginProtocol/dshop/blob/9ef5f0eb1fad1cae6de841f1154d695164ac0d82/backend/utils/deployShop.js#L277-L279

Should probably be `networkConfig.ipfs`

**Comment by franckc** [comment]
Fixed as part of deploy cleanup. Closing.
