### ISSUE TITLE
Add server side check on offers

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#17]
Currently the back-end does not perform any check to validate the offer data it receives before processing it.

We should add some checks on metadata such as
 - ID of the product
 - price

**Comment by DanielVF** [comment]
@Nick, I'm thinking the way to do this validation right will be to recalculate the price on the server from the items in cart object.

Seems like it would be good to:

- Document at least the contents of the cart object  (I've snagged it from the app, so I know what's there now)
- Add a version field to the cart object
- Create a method to calculate the price on an individual item, and another to calculate the order price. Share this method between the backend and the client code.

For the shared code, should we just created it in the dapp/shop code, and then require it from the backend? This is a little ugly, but it means we don’t have to create a new package, and the dapp code at least doesn’t have to know anything special is going on.

This sound good to you?

**Comment by franckc** [comment]
@DanielVF Are you actively working on this? If not I have cycles now so I can pick it up...

**Comment by DanielVF** [comment]
All yours!

**Comment by franckc** [comment]
Actually I think we should still work on this. Right now we don't validate enough the orders data before processing it, which is bad.

**Comment by franckc** [comment]
Closed vi #755
