### ISSUE TITLE
Offer finalization incorrectly requires to use the Buyer's wallet

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#176]
Steps to reproduce:
 - As buyer using Wallet B, buy a product using crypto
 - As merchant using Wallet A, accept the offer on the shop's admin Orders page
 - As merchant using Wallet A, try to accept the offer on the shop's admin Orders page
=> The UI rejects it with error: "Incorrect account. Please set account to <Wallet B>"

**Comment by nick** [comment]
Done now
