### ISSUE TITLE
Enable Sentry on the front-end

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#179]
Sentry = https://sentry.io

Before or soon after we launch the external deployer, it would be good to monitor crashes happening on the front-end.

We should be sensitive about user privacy. Some merchants may not want to share crash reports from their buyers.

This could be a per-shop configuration and during onboarding the merchant gets asked whether or not they are ok with "sharing buyers crash reports with Origin for improving the product".

CC @gullible1 to help defining the UI

**Comment by gullible1** [comment]
As discussed, let's do something [like this](https://docs.sentry.io/enriching-error-data/user-feedback/?platform=javascript):, with a "Thank you. Your feedback has been sent." message upon submission. @franckc 

We can add an option on the admin panel for the merchant to disable this completely if they want to, under a new "advanced settings" section, where we will be moving things like custom CSS and meta description to. It can just be a checkbox and a message along the lines of "Help us improve Origin Dshop’s stability and performance by sharing crash reports. If you do not want us to collect this data, you can opt out below." CC @nick
