### ISSUE TITLE
Add admin functionality to accept and finalize crypto offers

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#18]
Currently when a buyer pays in crypto, we have to accept the offer using shoporigin.com.

We should have functionality under the dshop admin to accept those offers.
This would call the marketplace contract and release the funds that were held in escrow.

**Comment by franckc** [comment]
Prioritizing this as a P2 for now since we have had so few crypto payments.

**Comment by nick** [comment]
We should also have an 'auto accept' function that automatically accepts an offer once validation has passed.

**Comment by nick** [comment]
Done
