### ISSUE TITLE
Error when connecting web3 wallet 

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#182]
![WhatsApp Image 2020-07-09 at 3 37 01 PM](https://user-images.githubusercontent.com/46481405/87032869-d746d000-c217-11ea-9b4a-da9466a452e6.jpeg)

After I logged in to my account for the first time and clicked on "Set up web3 wallet", clicking on "connect" on the /settings/payments tabs throws up the above error.

However, after I went to create a product and tried to publish my store, I was able to connect my web3 successfully via the "please connect a web3 wallet" prompt.

**Comment by gullible1** [comment]
This hasn't happened since - okay if I downgrade this while we keep an eye on it @nick ?

**Comment by nick** [comment]
Sounds good yea

**Comment by franckc** [comment]
All 3 of our internal testers ran into this issue while connecting their wallet in prod.
Bumping to a P0.

Might be somehow related to https://github.com/OriginProtocol/dshop/issues/216

**Comment by franckc** [comment]
More details from the internal testers:

**Matt**: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.0.1) 
Chrome: Version 83.0.4103.116 (Official Build) (64-bit)
Metamask: 8.0.4

**Kay**: Same message as Matt

**Amy**: Had to disable Privacy Badger extension in order for the wallet to connect (Chrome browser).

**Comment by shahthepro** [comment]
**Steps to reproduce**
1. Disconnect all addresses from Dshop on MetaMask.
2. Reload Dshop and create a new shop.
3. Go to `/settings/payment` and try to connect your wallet
4. Click "connect" on MetaMask

Was a little bit harder to debug but [got a fix here](https://github.com/OriginProtocol/dshop/commit/5cdcfa0e769036cbab272318e88b2be613c5cb3a). Basically, some props were not passed to `useEffect` and we didn't `await` one promise.

**Comment by gullible1** [comment]
Reopening this as Matt was prompted to connect to localHost and wasn't able to successfully connect his wallet. See testing video [here](https://www.loom.com/share/d1e74d219a8a4f8b884182f28a7482a4).

<img width="1419" alt="Screen_Shot_2020-07-20_at_4 51 35_PM" src="https://user-images.githubusercontent.com/46481405/88004096-e80d1500-cb38-11ea-9e6b-95142dc5e322.png">
