### ISSUE TITLE
Make listener multi-instance friendly

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#185]
The listener isn't entirely happy when multiple instances are running.  Often times every instance picks up an event and is in a race to add an order to the DB.  First one wins and the rest error with DB constraint errors.  There's probably other places where this can also be an issue.

Either the listeners need to be made idempotent, some kind of locking mechanism should be introduced, some kind of logical event sharding(meh), or we need some configuration allowing the listener to only run on one instance.  Leaning towards the first option even if it's a little redundant but will need to account for everything.

This kind of blocks infra scaling.

**Comment by nick** [comment]
Could we move the `handleLog` function in the listener to a queue? Then if we make sure the jobId is unique, that should [prevent duplicate](https://stackoverflow.com/questions/50446692/bull-queue-ensure-unique-job-within-time-period-by-using-partial-timestamp-in-j) events from being processed.

**Comment by mikeshultz** [comment]
Was just looking at the bull docks to see if there was a way to prevent dupes.  Will check out your link, thanks

**Comment by franckc** [comment]
An additional thing to think about if running multi-instances of the listener would be the cursor update. See https://github.com/OriginProtocol/dshop/blob/master/backend/listener.js#L170 It would not be good if multiple instances update that column in the DB.

Overall separating the API from the listener and running a single listener container while running multiple API containers might be a simple solution? And from an availability standpoint I think it would be acceptable since if what we mostly are about is keeping the API up while doing deployments.

**Comment by mikeshultz** [comment]
Thanks for the addition.  `handleNewHeads` can probably just have an extra WHERE clause to only update if the block number been an increase.

> Overall separating the API from the listener and running a single listener container while running multiple API containers might be a simple solution?

I'm not convinced it would be *that* simple.  Would require separating the code, adding new deployments, etc.  Just to save a little code adaptation that would add a bit of resilience to the listener setup.  I think I would rather have 2+ listeners acting in concert for a good HA setup rather than one and hope for the best.  Especially if the listener doesn't really handle historical data well.  If the necessary changes end up being a ton of work, I'll consider this but I really don't think it will come to that.

**Comment by franckc** [comment]
Yes, updating the row only for higher block number is a possibility.
Here is a possible way to do it:
 - Load and lock the row (using a FOR UPDATE statement)
 - Check block num value
 - Update it if needed
Here is an example of code showing how to lock a row using sequelize: https://github.com/oplabs/origin-deals-api/blob/master/src/logic/ogn.js
