### ISSUE TITLE
Unable to change shop name

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#186]
The user had set a store name (tshirtop.com) right at the beginning upon logging in to Dshop for the first time.
![Screenshot 2020-07-09 at 11 02 08 PM](https://user-images.githubusercontent.com/46481405/87064755-bcd61c00-c242-11ea-9576-769d4bb80331.png)

Then he wanted to change it to ofermizrachi.com, so he went to settings > appearance and updated the Store Name field.
![Screenshot 2020-07-09 at 11 07 12 PM](https://user-images.githubusercontent.com/46481405/87064897-e5f6ac80-c242-11ea-9ca3-41cb1b0df1e0.png)

He then clicked update and it said it was saved.

Upon going to the storefront, the shop name wasn't changed across all places (see image below).
<img width="269" alt="Screenshot 2020-07-10 at 12 11 56 AM" src="https://user-images.githubusercontent.com/46481405/87064957-fb6bd680-c242-11ea-9302-b39c1a8ec66f.png">

The user then tried to add a second shop after and name it tshirtop.com (his original choice) but it said the name was already taken.

If a user changes his shop name, the old name should be "available" once again for a new store to use.

**Comment by nick** [comment]
Will be fixed in next deploy
