### ISSUE TITLE
Unable to upload photo when adding new product 

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#187]
A user tried multiple times to upload photos for his product listing, both via drag &drop and also browsing his computer for the image. 

All of these attempts happened before his store has been deployed.

The image size was 7 MB.

We should show image requirements, if any, (e.g. maximum file size 1 MB) and visible errors if requirements aren't met.

**Comment by nick** [comment]
Fixed. Should resize pics now before uploading...
