### ISSUE TITLE
"Resend code" not working for email verification

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#188]
<img width="906" alt="Screenshot 2020-07-10 at 12 57 57 AM" src="https://user-images.githubusercontent.com/46481405/87068761-a3d06980-c248-11ea-928d-f04a2999e4f3.png">

Clicking "resend code" doesn't do anything. The user should be able to click it and receive a verification email (email copy [here](https://docs.google.com/document/d/1aWbO_eqQKsHCdRfnyPymKxMdn4RNXF5WUHZLnAjL9o0/edit)). Upon clicking the confirmation link, the user should be returned to the same page on Dshop.

**Comment by gullible1** [comment]
Adding @franckc since you're helping Shah to look into this (:

**Comment by micahalcorn** [comment]
I get "Failed to send email, check your email configuration settings".

**Comment by shahthepro** [comment]
@micahalcorn Can you try again now? I just reconfigured the email settings on prod after a deploy.

**Comment by shahthepro** [comment]
Closing this, since this works now

**Comment by micahalcorn** [comment]
It does, indeed, thanks.
