### ISSUE TITLE
Copy changes for "submitted to blockchain" modal

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#189]
![Screenshot 2020-07-10 at 12 54 42 AM](https://user-images.githubusercontent.com/46481405/87071083-4d652a00-c24c-11ea-92da-d4fde858b333.png)

Change "dismiss" to "hide" to more accurately convey what happens.

Add a subtext saying "You can continue to monitor this transaction in your wallet"

**Comment by nick** [comment]
Done
