### ISSUE TITLE
Error when adding custom ERC20 token as payment method

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#190]
<img width="546" alt="Screenshot 2020-07-10 at 1 39 36 AM" src="https://user-images.githubusercontent.com/46481405/87072437-535c0a80-c24e-11ea-8a4a-87cf561777c2.png">

Tried adding a variety of different tokens as a payment method but they all returned a "failed to fetch exchange rate of the token" error.

**Comment by shahthepro** [comment]
Seems like CoinGecko doesn't return prices for all the coins, not sure if it has to do anything with volume though.

**Comment by nick** [comment]
Perhaps we can offer a few different methods for exchange rate?

**Comment by micahalcorn** [comment]
I tried adding USDT as an accepted payment method. After clicking "Update", I saw "Saved OK" but it disappeared from my Accepted Tokens and seems to have been lost. I tried that a few times with the same result. Then I thought to refresh the page and now it's back with the "changes that have not been published" alert, which makes sense.
