### ISSUE TITLE
New user signup flow

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#205]
When we open Dshop to the public, new merchants will need to be able to go to api.ogn.app to create Dshop accounts. If they already have an account, they have the option to sign in instead (what we currently have when we go to api.ogn.app).

Here are the mocks [on Zeplin](https://zpl.io/Vxxez93).

- [ ] If the merchant chooses a store name that is taken, an error message should show up saying "A shop with that name already exists."
- [ ] When hovering over the "i" next to Shop Name, the help text should say "Your shop's default domain will be shopname.ogn.app. You can still change your name after you open your shop."

In the interest of time, please feel free to skip ["signup 2"](https://zpl.io/VKZ8RBJ) and ["signup 3"](https://zpl.io/a8o4gD6) and bring the user to directly to the [admin home screen](https://zpl.io/br56BKr).

**Comment by nick** [comment]
Kept it simpler for now and separated Create Shop from the signup flow...
