### ISSUE TITLE
"This shop already exists" error for a new store

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#209]
When I signed into a new account for the first time, clicked "add store" and was prompted to name my shop, I received the error "this shop already exists" for the first two times, and it only went through on the 3rd try.

However when I logged in again, all 3 stores had been created under the account.

<img width="1329" alt="Screenshot 2020-07-14 at 7 26 51 PM" src="https://user-images.githubusercontent.com/46481405/87420763-6a14af80-c608-11ea-8bd9-cb3908157d74.png">

**Comment by franckc** [comment]
Setting priority to P1 since that impacts new users and could be a very bad first-time experience.

@gullible1 Was there any error in the browser javascript console?

**Comment by nick** [comment]
Fixed in next deploy
