### ISSUE TITLE
"Incorrect network" error when connecting web3 wallet

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#216]
<img width="684" alt="Screenshot 2020-07-15 at 11 55 52 PM" src="https://user-images.githubusercontent.com/46481405/87567377-cce47480-c6f6-11ea-886e-96e9bcb110ec.png">

2 of our beta testers ran into the "incorrect network" error despite their Metamask being on Mainnet. Logging in and out of Metamask, toggling between mainnet and testnets on Metamask, and leaving the page and coming back to it all didn't help.

**Comment by nick** [comment]
@gullible1 are you able to reproduce this now?

**Comment by gullible1** [comment]
@nick I haven't been able to reproduce this at all on my end, but the user who ran into this managed to connect his wallet 15 minutes ago. His Metamask showed a successful transaction but on Dshop it still showed his wallet as not connected. @shahthepro mentioned that he believes the missing await is the issue, and that there's a fix for that on prod.

Okay if I downgrade this for now from p0?

**Comment by franckc** [comment]
@shahthepro fixed this. closing.

**Comment by mikeshultz** [comment]
![incorrect_network](https://user-images.githubusercontent.com/1048089/88327001-e0d63a80-cce3-11ea-81d9-ca186fab839a.png)

I'm apparently able to repro this locally when trying to use Rinkeby.  No errors in console.

**Comment by gullible1** [comment]
2 of our new users are also reporting the same issue (Metamask on mainnet, wallet fully funded with ETH).

**Comment by shahthepro** [comment]
@gullible1 Which shop? Was it redeployed after the fix went live? The shop needs to be redeployed before the fix can work.

**Comment by nick** [comment]
Hoping this is fixed now. Will monitor...

**Comment by gullible1** [comment]
Will bump it down from P0 as it seems to be fine for now..

**Comment by nick** [comment]
Will close this for now. Can re-open if we find it's still an issue...
