### ISSUE TITLE
Store shop's private key server side and use it for marketplace listing creation/updates

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#22]
Currently when setting up a shop the super-admin has to use their web wallet (ex: metamask) to create a listing on the marketplace contract. Later, when the shop admin wants to export the shop's product data to BigQuery, they also have to use their web wallet to issue a "ListingUpdated" event on the blockchain.

We'd like to change that so that during the store setup, we prompt the super-admin for the shop's private key and store it in the encrypted configs in the DB. The back-end can then use the priv key to send transactions to the marketplace contract for listing creation and update.

Note that the back-end will then store two private keys:
1. shop private key, used for listing creation, listing updates
2. buyer private key, used for creating offers on the marketplace for credit card payments

**Comment by franckc** [comment]
CC @nick @mikeshultz in case they have any comments.

**Comment by nick** [comment]
This is done now... PK is stored in shop config
