### ISSUE TITLE
[Checkout flow] Failure to fetch exchange rate on the payment page

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#226]
While testing on prod, Amy got the following failure on the checkout flow.
<img width="487" alt="ExchangeRateFailure" src="https://user-images.githubusercontent.com/945910/87625806-eaf2aa80-c6df-11ea-8ac0-4205f080488d.png">

**Comment by shahthepro** [comment]
@franckc Do you happen to know which shop it is?

**Comment by franckc** [comment]
I believe it is https://amys-store.ogn.app/

**Comment by franckc** [comment]
Though I just tried Amy's store and was not able to reproduce it... :(

**Comment by amyhockings** [comment]
Was a tracking blocker extension causing the issue
