### ISSUE TITLE
[Admin] Failure to save shop logo 

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#227]
Matt: When I save, I don't get any notification. I also see this console error.
```
VM6:1 POST https://dshopapi.ogn.app/shops/test-shop-1/save-files 401
app.9f163fad.js:1 Error
    at app.9f163fad.js:1
````

Amy: Logo doesn't save/no notification that changes have been made. Favicon/SM/other detail fields worked.

**Comment by franckc** [comment]
@matthewliu I was not able to reproduce. Could you share the file you tried to save as logo?

Amy: could you please do the same?

**Comment by matthewliu** [comment]
@franckc i uploaded this image.

https://dshopapi.ogn.app/test-shop-1/Screen_Shot_2020-07-07_at_4.39.18_PM.png

**Comment by shahthepro** [comment]
**Steps to reproduce:**

1. Add a Admin (not superadmin) user to the shop
2. Login as the new admin user
3. Add something in "About your store" field and then click "Save".

Basically, this is a permission issue, the admin cannot update site's about file (only superadmin can). I'm not sure if we should let that happen. What do you think? @nick @franckc

**Comment by shahthepro** [comment]
Have pushed [this changeset](https://github.com/OriginProtocol/dshop/commit/e9cd9d5ddd082339491156d9dd6b532c83a7b974) to a branch. This should allow admin to update about file. Let me know if that behaviour should be changed.

**Comment by franckc** [comment]
I think it does make sense. Admin should have full-control over a shop settings and look & feel.
Marking this as closed.
