### ISSUE TITLE
[Checkout flow] Failure to pay with a credit card

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#228]
Matt ran into an following error when attempting to pay for a product on his test shop with a credit card.
He got this in the browser JS console:
```
Matt: VM52:1 POST https://test-shop-1.ogn.app/pay 405
(anonymous) @ VM52:1
(anonymous) @ 4.9f163fad.bundle.js:1
is @ vendors~app.9f163fad.bundle.js:55
gu @ vendors~app.9f163fad.bundle.js:55
e.unstable_runWithPriority @ vendors~app.9f163fad.bundle.js:63
qi @ vendors~app.9f163fad.bundle.js:55
mu @ vendors~app.9f163fad.bundle.js:55
(anonymous) @ vendors~app.9f163fad.bundle.js:55
U @ vendors~app.9f163fad.bundle.js:63
k.port1.onmessage @ vendors~app.9f163fad.bundle.js:63
/#/checkout/payment:1 Uncaught (in promise) SyntaxError: Unexpected token M in JSON at position 0
```

**Comment by shahthepro** [comment]
The URL should have been `https://dshopapi.ogn.app/pay` or `https://api.ogn.app/pay`. Checking the config on that shop, it seems config.backend is set correctly. I'm not sure what else could have caused. I cannot reproduce that.

<img width="316" alt="Screenshot 2020-07-16 at 4 21 27 PM" src="https://user-images.githubusercontent.com/10547529/87662805-6b68e800-c780-11ea-96d8-2a3db3a0f46e.png">

Most probably, the config didn't load. I'll add a check for that. But, cannot say for sure that'll stop this from happening completely.

**Comment by shahthepro** [comment]
Okay, on a closer look, we use `config` inside `useEffect` but it was not listening to changes on `config`. 
Here's my theory: 
1. `config` took some time loading
2. The component mounted and `useEffect` ran once before `config` was loaded, making it freeze and use an empty object as `config`

If my assumption is true, [this should fix this](https://github.com/OriginProtocol/dshop/commit/810acce37f067afc002379714aa39cb9bdbf5739).

**Comment by franckc** [comment]
Marking this as closed. Let's re-open if this happens again.
