### ISSUE TITLE
Store shop's IPFS hash in the DB

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#23]
Currently when the super admin deploys a store, we don't record the IPFS hash of the deployed store in the DB.

It would be convenient to have this information. For example:
- To show it in the admin UI
- For internal server operations, such as verifying an offer coming from the front-end against the products metadata stored in IPFS (ex: price, product ids, etc...) - See #17 
 - To keep track of what version of the code a shop is running
- Others?

In terms of implementation, we could add a new column "ipfs_hash" to the existing "shops" DB table. Alternatively, if we want to keep track of older versions of the shop that were published, we could create a new DB table "shops_ipfs" with each row storing a hash and a shop_id (e.g. 1 to many relationship between a row in "shops" and rows in "shops_ipfs").

**Comment by franckc** [comment]
CC @nick @mikeshultz for comments/thoughts

**Comment by mikeshultz** [comment]
I think a `shop_deployment` table would be useful where it tracks versions and deployment hashes cold be useful.

**Comment by DanielVF** [comment]
Seems very important to store this. I'd definitely go with keeping track of each version, and like @mikeshultz's suggested name.

**Comment by franckc** [comment]
Agreed. And yes, shop_deployment is a much better name... thanks naming wizard @mikeshultz !

**Comment by franckc** [comment]
Done.
