### ISSUE TITLE
[Shipping] Free shipping option is automatically created

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#235]
Our internal testers were caught off guard when after they added their first product a free shipping option was automatically added and the "Setup your shipping option" task on the Home page got marked as complete.

Feedback:
```
Matt: It appears this was checked as complete? But I didn't actually go through the process yet. Was this automatically created with the first product without my knowledge?

Kay: I saw a default shipping option was already added "Free Shipping $0 Rest of the world Arrives in 10 to 14 days". Not sure if this was on purpose?

Micah: Same for me: a green checkmark even though I haven't looked at this section yet.
```

@gullible1 What do you suggest the UI flow should be like?

**Comment by gullible1** [comment]
@franckc The "setup your shipping option" task should definitely not be marked as complete before the user has taken any action.

[Here's an improved UI](https://zpl.io/brBz3MW) for the /settings/shipping page (not a blocker for this launch). At some point in the near future we will want to allow product level shipping settings and move this to the "Add product" page.

This should address #230 as well.
