### ISSUE TITLE
[Payment] Stripe public key not saved in config

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#236]
I noticed we save the private key and the webhook secret but not the public key.
It threw me off when I looked at my shop's Stripe config after configuring it since I though I had missed something.

<img width="516" alt="Screen Shot 2020-07-15 at 5 00 27 PM" src="https://user-images.githubusercontent.com/945910/87698128-e6fa7300-c747-11ea-86ad-3b30fa3e25f3.png">

@nick @shahthepro Is there any reason why we don't store the stripe public key?

CC @gullible1 as a FYI

**Comment by shahthepro** [comment]
We actually store them but in config.json file. It wasn't loaded properly in the UI, I think

**Comment by franckc** [comment]
Ah... got it. Yep makes sense to store in config.json
