### ISSUE TITLE
Replace web3 with ether.js

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#24]
Ether.js is arguably much better than web3: the API is cleaner and leaner. You can define the ABI inline, etc...

I'd vote for us to completely deprecate our usage of web3 and to only use ether.js, both on the fron-end dand bakc-end.

**Comment by franckc** [comment]
CC @nick @mikeshultz @DanielVF For any thoughts/objections.

**Comment by DanielVF** [comment]
I've not used it, but it sure looks way better in the documentation!

**Comment by nick** [comment]
Heads up that we should use [v5](https://docs-beta.ethers.io/api/) of Ethers

**Comment by nick** [comment]
I guess we can call this done, even though we're still using it via Truffle to deploy contracts.

**Comment by DanielVF** [comment]
Looks like the following files are still requiring web3:

- backend/listener.js
- backend/listener.js
- backend/scripts/backfill.js
- backend/utils/createListing.js
- backend/queues/makeOfferProcessor.js
- backend/scripts/updateListing.js
- backend/utils/address.js
- backend/utils/handleLog.js
