### ISSUE TITLE
Use bullets to delineate the custom DNS records

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/dshop#241]
We should make it more obvious that these are two separate DNS records. I initially copied it thinking it was a single TXT record. Bullets would be an easy fix.

![Screen Shot 2020-07-16 at 1 23 37 PM](https://user-images.githubusercontent.com/982234/87719243-e96cc500-c767-11ea-81b6-2a5f1698dce1.png)

**Comment by micahalcorn** [comment]
Same here, and it's not clear what the host value should be for something.com (* vs @ vs www).
