### ISSUE TITLE
Product images fail without error message

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/dshop#243]
I uploaded this beautiful picture of my product:

![crayola](https://user-images.githubusercontent.com/982234/87721278-0951b800-c76b-11ea-85b8-30d1226fc708.jpg)

Everything seemed to work, but my product still shows as:

![Screen Shot 2020-07-16 at 1 48 58 PM](https://user-images.githubusercontent.com/982234/87721323-1cfd1e80-c76b-11ea-9192-734301eb44f0.png)

Tried some other images but they failed too.

**Comment by franckc** [comment]
@joshfraser I tried adding the image to one of my shop and it worked. Wonder if GitHub upload modified it. Do you have a google drive link to the origin image?

**Comment by mikeshultz** [comment]
You're looking at the "preview" shop and not a deployed instance, yeah?

**Comment by joshfraser** [comment]
Yes, the preview version. A separate issue is my deployed version isn't showing up yet. Not sure if that's due to slow DNS propagation or the Ethereum network being clogged up?

Here's the link to the image:
https://drive.google.com/file/d/1276UDb-VGMLbsXUYB8xMD-0cuUjD9XVT/view

Perhaps more useful are my console logs:

![Screen Shot 2020-07-16 at 3 04 39 PM](https://user-images.githubusercontent.com/982234/87727903-d7dee980-c776-11ea-884e-c6af1c8c7203.png)

**Comment by mikeshultz** [comment]
That 401 on `/products/upload-image` seems relevant.

**Comment by mikeshultz** [comment]
@joshfraser can you look at your networks tab and look at what the full URL is for that?  That endpoint doesn't intentionally return a 401 unless you fail auth.  Might be worth going to `https://same-hostname/auth` and see what happens.

**Comment by joshfraser** [comment]
Good call @mikeshultz. Image uploads work on `dshopapi.ogn.app` but not `dshop.originprotocol.com`

**Comment by mikeshultz** [comment]
There's a lot of weirdness going on right now with the hostnames switching up.  I think some configurations are probably pointing at backends that you may have no logged into.  Maybe try to login directly do https://dshop.originprotocol.com, if you can.

And if you're feeling like you want to be a power-tester, maybe log out of https://dshopapi.ogn.app and note wherever you see an auth failure.

**Comment by mikeshultz** [comment]
Haven't been able to repro this directly and just want to chalk this up to auth weirdness between the move to the new domain.  @joshfraser, is everything working now?  Okay to close?

**Comment by mikeshultz** [comment]
Gonna close this for now unless @joshfraser tells me otherwise.
