### ISSUE TITLE
The "Verify your email" task does not show as completed after merchant verifies their email

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#252]
To reproduce:
 - signup for a new merchant account
 - on the home page, click on "Verify your email"
 - look for the email in your inbox and click on the link
 - land on the Settings > User page (https://dshop.originprotocol.com/#/admin/settings/users)
 - go back to the home page
=> The "Verify your email" task does not show as completed.

**Comment by shahthepro** [comment]
Works fine for me on local. Which shop it is?

**Comment by matthewliu** [comment]
@franckc it works fine for me as well. Here's a minor gripe. My email and dshop were in separate browsers (one is incognito). So I verified in one and it just took me to the sign up screen. There was no indicator that the email had been verified. We probably should put up a small toast "Thanks for verifying" even if the user is not logged in.

Also, this to me should be done right after account sign up. It's weird to have to click on Verify email to trigger it.

**Comment by franckc** [comment]
@shahthepro shop FranckTest3. Note that if I refresh the page it correctly shows that task as completed. So must be a UI related thing...

**Comment by franckc** [comment]
Works for me now. Marking as closed.
