### ISSUE TITLE
Login failure when switching to a different merchant account

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#253]
To reproduce:
 - Login to the admin using merchantA account
 - Logout
 - Login as merchantB

The UI gets into an infinite lop where it keeps sending /auth requests to the back-end until nginx refuses further requests and sends a 503.

<img width="1292" alt="Screen Shot 2020-07-16 at 9 44 11 PM" src="https://user-images.githubusercontent.com/945910/87749441-8b62d080-c7ad-11ea-80d5-9b5c591ce76e.png">

**Comment by shahthepro** [comment]
I had seen the infinite auth requests when there is no-such-user error sent by server. Didn't dig deep into it, since I had manually deleted sellers from DB on local.

**Comment by franckc** [comment]
After clearing my cookies/localstorage, i'm able to login.
