### ISSUE TITLE
Backend failed to read the product's data.json

### ISSUE THREAD

**Issue by shahthepro** [OriginProtocol/dshop#255]
Matt was trying to delete a product but it failed with "No such product" error. ~~On a closer look, The frontend was loading the product's data file `data/yet-another-product/data.json`  but the backend check `fs.existsSync()` for the file `data/yet-another-product/data.json` failed.~~

~~Few more things:~~
- ~~The file `data/yet-another-product/data.json` did exist (unless the cache was being served to the frontend through CDN, but I doubt we use CDN or caching for these files).~~
- ~~It worked fine after I made a change to the product and saved it (which would have created/updated the data.json file).~~

There is no way to reproduce this, at present.

**Update:** I was wrong about data.json being missing. The product ID was missing from `products.json`. Not sure, how that ID could be missing, when frontend reads from the same file too.

**Comment by mikeshultz** [comment]
Worth noting this was the identified as the source of the error message:

https://github.com/OriginProtocol/dshop/blob/25616b79375ba2f97803b5d65130540facb30993/backend/utils/products.js#L191-L199

> unless the cache was being served to the frontend through CDN, but I doubt we use CDN or caching for these files

Correct, though browser caching could be worth considering.  Chance the server could also have just responded 304 or something like that assuming the file wasn't deleted.

According to Matt this happened when he was trying to delete the product.  There's a video but I haven't reviewed it yet.

**Comment by mikeshultz** [comment]
304s and browser caching seem pretty likely.  This was provided by @amyhockings in Discord:

<img width="859" alt="Amys304s" src="https://user-images.githubusercontent.com/1048089/87800223-5ab18400-c80b-11ea-9cf5-dda2fe2b7afd.png">

**Comment by shahthepro** [comment]
@mikeshultz I did have "Disable caching" enabled (and DevTools open), and it still loaded the file fine on frontend

**Comment by mikeshultz** [comment]
Error seen by users:

<img width="1042" alt="NoSuchProduct" src="https://user-images.githubusercontent.com/1048089/87800831-225e7580-c80c-11ea-9d46-4e426d129ca3.png">

**Comment by mikeshultz** [comment]
> I did have "Disable caching" enabled (and DevTools open), and it still loaded the file fine on frontend

@shahthepro  When you say it loaded fine, do you men you did not see this error when you would have expected to see it?

**Comment by shahthepro** [comment]
I mean the `data.json` and `products.json` loaded fine in frontend (with 200 status code). 

Okay, I didn't much attention to the code, at first glance. Seems like I'm wrong about `data.json` being missing. I was looking at [here](https://github.com/OriginProtocol/dshop/blob/master/backend/utils/products.js#L197) instead of [here](https://github.com/OriginProtocol/dshop/blob/master/backend/utils/products.js#L256). So, if anything, a product with that id was missing from `products.json`. Don't think the file was missing or it is related to GCP Filestore. It could be something else.

Sorry about the misunderstanding, will update the issue description.

**Comment by mikeshultz** [comment]
@shahthepro  Alright, assigning back to you then.  Let me know if I can help.

**Comment by matthewliu** [comment]
I've reproduced the issue with a Loom video. This might be helpful.

https://www.loom.com/share/88220a50555f4aa189e41a9347484e61

**Comment by matthewliu** [comment]
We hypothesize that the same issue is causing problems for Collections.

Here's another video.

https://www.loom.com/share/71fb48c2126a472f9376d5ee601360eb

**Comment by franckc** [comment]
@Nick thinks he fixed it in https://github.com/OriginProtocol/dshop/commit/41cbfe58acdc9214fb4ba78d45c578071fb128a0

His fix is on staging. We are going to bake it over the week-end and will deploy for validation to prod on Sunday night / early Monday when eng folks are awake to make sure it does not break anything else.

**Comment by shahthepro** [comment]
Turns out `require(file)` loads the file only once and uses the cache from second time. Replaced that with `fs.readFileSync` in [this changeset](https://github.com/OriginProtocol/dshop/commit/a31063596a86f582c7aab8d9e2703c9725076867). However, if you have a stray product in your products.json, it is gonna stay there. Deleting again should work though. If not, can write a script to remove these stray products
