### ISSUE TITLE
Create a shoop button doesn't work

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#257]
### Description 

On initial setup, after creating the super user and network settings, the "Create a shop" button doesn't seem to work.  Or do anything.

Button in question:

![create_a_shop](https://user-images.githubusercontent.com/1048089/87807645-bd0f8200-c815-11ea-9335-bb7aa36ad3b1.png)

This is the only thing that shows when visiting the backend URL.  While I don't think this is release blocking since we have initial stores already, it is blocking my local testing for other work.

### Repro steps

1) Destroy local SQLite DB and run migrations
2) Run backend
3) Go to http://localhost:9000 and follow the prompts

**Comment by nick** [comment]
Not sure why the button says 'shoop' - searching the codebase for 'shoop' returns nothing. Is it somehow running old code?

**Comment by mikeshultz** [comment]
Looks like this is preventing display of the Nav & modal:

    if (!localStorage.isAdmin || !admin) {
      return null
    }


Ha, the `shoop` change was actually so I could identify the correct button because there's two `Create a shop` buttons in the FE code.  That was a local-only change.  The button in question is in `StoreSelector`.

**Comment by mikeshultz** [comment]
So, `localStorage.isAdmin` is `undefined` for me, which would make `useAuth` not run at all.

    useAuth({ only: () => localStorage.isAdmin })

And that never gets set because of this:

https://github.com/OriginProtocol/dshop/blob/7863f4e682baa893386eaa3bc8f23bf83d777a81/shop/src/utils/useAuth.js#L34-L36

And the backend returns `sucess: false` because of this: 

https://github.com/OriginProtocol/dshop/blob/7863f4e682baa893386eaa3bc8f23bf83d777a81/backend/routes/auth.js#L149-L159

There's a lot of subtle interactions going on here.  Wondering if we should make this dummy-obvious.  `success: false` for any reason other than a request failure seems risky.
