### ISSUE TITLE
Copy shop URL

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/dshop#259]
As a seller who just published my shop, I want to share the public URL around social media, etc. There should be a prominent place where I can see it and, ideally, click to copy it to my clipboard. Maybe when I toggle my view to "Storefront" it should be visible. Or there should be something under "Congratulations on your new shop" that encourages me to share the URL. I think I'm currently only able to copy it from Settings > Publish.

**Comment by phyninja** [comment]
Hello Micah, 
I'm not sure if there is still interest in this. If there is, would you mind sharing what you meant by toggling your view to Storefront?

**Comment by franckc** [comment]
Implemented in #909
