### ISSUE TITLE
Inconsistent "About" text

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/dshop#266]
Consider letting shop creators remove our "About" copy. I thought that it was a placeholder, but it remained intact after I added something to "About your store".

<img width="625" alt="Screen Shot 2020-07-17 at 10 34 30 AM" src="https://user-images.githubusercontent.com/273937/87815122-e7fbd500-c819-11ea-9f84-4ed7d9cf6976.png">

**Comment by matthewliu** [comment]
Yeah, I also don't think this should be in the About section at all (even as a placeholder). It's a turn off to buyers.

If we want to have a separate section that allows people to learn more about the app (we should have a Powered by Origin that expands to show something like this). But it shouldn't be so loud by default.
