### ISSUE TITLE
Better UI/documentation for configuring Stripe

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#271]
@kayyoo23 reported that during Round 2 of testing on her shop https://kay-store.ogn.app:
- she purchased an item via credit card
- she did NOT receive any confirmation email
- the order is NOT showing up in the Orders page on her shop's admin

**Comment by franckc** [comment]
I checked "Kay Store"'s configs. The Stripe configuration has an incorrect value for the "Stripe Webhook Key".

<img width="499" alt="Screen Shot 2020-07-18 at 9 50 29 PM" src="https://user-images.githubusercontent.com/945910/87867431-8f275c00-c941-11ea-9bcc-7bd3883de1b9.png">

The key is not an URL but rather a "signing secret".  It's a bit tricky to find it in the Stripe UI. Here is how to get it:
 - click on "Developers" on the left hand menu
 - click on "Webhooks"
 - click on the webhook https://dshopapi.ogn.app/webhook to get its details
 - On the webhook details page, look under "Signing secret"

Also, I noticed the shop was set up with Stripe's test public and secret keys. This is totally fine, but then the tester has to make sure to use a test credit card number (as described in [this doc](https://stripe.com/docs/testing)). Otherwise using a real credit card with test keys will fail.

It's probably worth having some extra details on the Stripe config modal for each of the 3 different fields. And/Or a link to a doc where we explain to the dshop merchants how to configure their Stripe integration.
CC @gullible1 

There is no bug, but there are some good UI learnings that probably want to act on.
Lowering to P2, changing to feature request and assigning to @gullible1 to decide what we want to do.

**Comment by kayyoo23** [comment]
> I checked "Kay Store"'s configs. The Stripe configuration has an incorrect value for the "Stripe Webhook Key".
> 
> <img alt="Screen Shot 2020-07-18 at 9 50 29 PM" width="499" src="https://user-images.githubusercontent.com/945910/87867431-8f275c00-c941-11ea-9bcc-7bd3883de1b9.png">
> 
> The key is not an URL but rather a "signing secret". It's a bit tricky to find it in the Stripe UI. Here is how to get it:
> 
> * click on "Developers" on the left hand menu
> * click on "Webhooks"
> * click on the webhook https://dshopapi.ogn.app/webhook to get its details
> * On the webhook details page, look under "Signing secret"
> 
> Also, I noticed the shop was set up with Stripe's test public and secret keys vs production keys (notice the prefix pk_test and sk_test). This is totally fine, but then the tester has to make sure to use a test credit card number (as described in [this doc](https://stripe.com/docs/testing)). Otherwise using a real credit card with test keys will fail.
> 
> It's probably worth having some extra details on the Stripe config modal for each of the 3 different fields. And/Or a link to a doc where we explain to the dshop merchants how to configure their Stripe integration.
> CC @gullible1
> 
> There is no bug, but there are some good UI learnings that probably want to act on.
> Lowering to P2, changing to feature request and assigning to @gullible1 to decide what we want to do.

Ah, I've put the wrong webhook key! Sorry for the confusion @franckc , my fault. Yup I used a test credit card number from Stripe (as I saw a modal that prompted me to use a test CC), but will make sure to use the correct stripe info for my next round of testing. Thank you for looking into this. :pray:

**Comment by gullible1** [comment]
Closing this as I've written [a help article](https://help.originprotocol.com/hc/en-us/articles/360052463013-How-do-I-connect-my-Stripe-account-to-my-store-) on this.
