### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#281]
- Phase I
  - Enable GA for all deployer admin pages. Data should get logged in Origin's GA account.
  - It should be completely disabled for all buyer side pages
- Phase II
  - Allow a merchant to turn on GA for the buyer side pages of their shop by providing a GA key in the deployer admin settings.

CC @gullible1 and @matthewliu to make sure we are on the same page on these requirements and also to determine priority (I think we should do phase I asap).

**Comment by gullible1** [comment]
@franckc agree phase 1 should be done ASAP. We should have it in place when we do the public announcement around the first few days of August.

For phase 2, we can have something simple like this to allow the merchant to enable GA on their store:
<img width="775" alt="Screenshot 2020-07-22 at 9 24 10 PM" src="https://user-images.githubusercontent.com/46481405/88181852-01f64700-cc62-11ea-955b-6cba0cbb6573.png">

**Comment by nick** [comment]
I've added support for GA for the deployer and added a new property to Origin Analytics. Right now it just tracks pageviews, we can always expand it to track more things later. I suspect 90% of our users have an ad-blocker, so not really sure how effective this is going to be 🤷‍♂️

**Comment by nick** [comment]
Reducing to P1 as we now have basic analytics

**Comment by franckc** [comment]
Phase II is tracked via #323 

Closing this now.
