### ISSUE TITLE
DNS changes still not propagated after 16 hours

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#282]
One of our users is having trouble verifying his DNS records after 16 hours.

<img width="498" alt="Screen_Shot_2020-07-22_at_05 56 55" src="https://user-images.githubusercontent.com/46481405/88168948-c3569180-cc4d-11ea-937e-22c015c9f406.png">

**Comment by gullible1** [comment]
@mikeshultz it seems like https://shop.sousvide.co.za/#/ is already working, but it still says his DNS changes haven't propagated yet. I don't think that domain has TXT records set, are they mandatory? How can I help this user fix this?

**Comment by mikeshultz** [comment]
Records look fine, so it's probably in the verification code.  Will take a peek. 

CNAME to our balancer:

    $ dig shop.sousvide.co.za

    ; <<>> DiG 9.16.3 <<>> shop.sousvide.co.za
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14092
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ; COOKIE: be2ae3467a9e5be88e06c9715f186337ae4a1b4e8f945316 (good)
    ;; QUESTION SECTION:
    ;shop.sousvide.co.za.       IN  A

    ;; ANSWER SECTION:
    shop.sousvide.co.za.    14388   IN  CNAME   fs-autossl.ogn.app.
    fs-autossl.ogn.app. 286 IN  A   35.230.101.134

    ;; Query time: 96 msec
    ;; SERVER: 192.168.1.1#53(192.168.1.1)
    ;; WHEN: Wed Jul 22 10:03:03 MDT 2020
    ;; MSG SIZE  rcvd: 124

IPNS TXT:

    $ dig TXT _dnslink.shop.sousvide.co.za

    ; <<>> DiG 9.16.3 <<>> TXT _dnslink.shop.sousvide.co.za
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31172
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ; COOKIE: 97356ef0ca37cf5feb9d78415f186341d4c260f6c36578bb (good)
    ;; QUESTION SECTION:
    ;_dnslink.shop.sousvide.co.za.  IN  TXT

    ;; ANSWER SECTION:
    _dnslink.shop.sousvide.co.za. 3600 IN   TXT "dnslink=/ipns/sousvide.ogn.app"

    ;; Query time: 56 msec
    ;; SERVER: 192.168.1.1#53(192.168.1.1)
    ;; WHEN: Wed Jul 22 10:03:13 MDT 2020
    ;; MSG SIZE  rcvd: 128


As seen by our IFPS node:

    # ipfs resolve /ipns/shop.sousvide.co.za
    /ipfs/Qmd1EcA4MtRZP2HKTNPmAb5B43A4MnvNpF9sThGyZSm5sG
