### ISSUE TITLE
Let merchant add manual payment methods

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#287]
Let merchants accept custom payment methods that are processed outside of their Dshop (e.g. bank transfers, cash on delivery etc).

They should be able to:

- [ ] Click on "Add payment method" under Manual Payment Methods ([see on Zeplin](https://zpl.io/VKR5GDX))
- [ ] Set up their manual payment method by proving a name (e.g. Bank transfer), description that shows up on payments page during checkout (e.g. Pay by bank transfer) and payment instructions that shows up on the order confirmation (e.g. send the payment to this account) - [See on Zeplin ](https://zpl.io/brBj1ve)
- [ ] Go to their Orders page and mark orders as "paid", once they receive the payment ([See on Zeplin](https://zpl.io/bzEJ183))

**Comment by shahthepro** [comment]
@gullible1 Have one question regarding "Mark as paid" button. Should we show up a modal or something with a notes field before the transaction? Could be useful for the seller to add a Transaction ID or some other things that he can refer later.
