### ISSUE TITLE
Rename "authTokens" throughout code

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/dshop#29]
Auth tokens are actually just a shop identifier, used so that the code can know which shop web actions are for. They aren't secret, and are not used for authentication.

Two open questions for @nick. What do we call its replacement? And you had mentioned including it in the the URL instead. Does this means that all backend urls would be in the form of /myshop/auth/login?

**Comment by nick** [comment]
slug? idStr? I think shopId would be ideal but I guess we already have an integer for that... unless we distinguish between 'id' and 'shopId' with the latter being the string version. 🤷‍♂️

**Comment by DanielVF** [comment]
"slug" seems like a good name.

**Comment by nick** [comment]
Another reason to have the ID in the URL instead of headers is it makes logs easier to look at, ie which shop is being hit

**Comment by mikeshultz** [comment]
They aren't secret but:

- They can be changed
- They prevent mass intelligence gathering through scripting(iterating `i++` on every URL)

If you think logs are important enough, that's fine but we never really do analytics via logs.

**Comment by phyninja** [comment]
@DanielVF, @nick [cc @mikeshultz]

> Would one of you please review the PR and/or leave me comments?

I'm checking in, as I haven't seen a response to the question above. 

Best,
Rajath

**Comment by franckc** [comment]
Given we don't have good test coverage of the back-end and front-end, I'm worried this would introduce bugs.
Overall I don't think this is a priority.
