### ISSUE TITLE
[Payment settings] Failure to save new custom token 

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#297]
Tried adding the NPXS token as a payment method. It seems to be added successfully and shows up on the list of crypto payments but disappears when I click "update".

Probably related to #295 .

Video [here](https://www.loom.com/share/a26ee30e64d84b31a31a1dcb2925863e)

**Comment by gullible1** [comment]
Update: the NPXS token showed up on the payment settings page after a few hours.

**Comment by nick** [comment]
Should be fixed by #340
