### ISSUE TITLE
[Payment settings] Stripe webhook issues

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#298]
One of our users received an email from Stripe notifying him that they are having trouble sending requests to a webhook endpoint associated with his Dshop.

You can see the full email [here](https://docs.google.com/document/d/1_gMWMw5DCM_aJO2Q3N8JUGBapDXyHRVJHAB9xe7DN00/edit?usp=sharing).

**Comment by franckc** [comment]
@gullible1 Do you know which dshop this is for?

**Comment by gullible1** [comment]
@franckc this is for sousvide.ogn.app.

**Comment by mikeshultz** [comment]
Can you instruct the user to get us information from the link in the E-mail?  

https://dashboard.stripe.com/events

The E-mail linked doesn't provide enough troubleshooting information.

**Comment by gullible1** [comment]
Have requested.

**Comment by mikeshultz** [comment]
If it helps, what we're looking for is the information from the Stripe dashboard under Developers -> Webhooks -> Webhook Attempts.  Anything useful from there.

Just be careful posting it here because some of it has PII.

Ref: #307 and #310

**Comment by franckc** [comment]
FYI this morning I ran the script that reconciles Stripe events with rows in the orders table.
```
node validatePayments.js --type=payment --allShops
```
It did not find any inconsistencies for shop id 52 (name "sousvide"). Here is the output:
```
Found 2 orders with encrypted hashes
Found hash QmdEM4An4PrzZ9vEVfDqvX8VCkyHEEVkwraehoyaq3y2Cu OK
Found hash QmPWx5bJ8EAqF2LDUdY5aDqN4LBRinkxPUUECfs8UCG9VQ OK
```

**Comment by mikeshultz** [comment]
Still waiting on information from the user, but wanted to write this down before I forget.

I suspect this might have to do with Stripe API versions. Reporting user is setup using `2015-08-07`.  The changelog in the docs don't even mention webhooks, so I can't confirm it yet.  Upgrading the API version may have other impacts for the user, however. And there doesn't appear to be any way for me to test a specific older version to verify.

No action to come from this just yet, just adding detail.

**Comment by mikeshultz** [comment]
These webhook requests don't make it to the external_payments table.  I have Stripe event IDs and they don't return any events from that table.  So this does not appear related to #319

**Comment by mikeshultz** [comment]
The data Stripe is sending us doesn't make any sense to me.  I'm betting this was created with some other eCommerce software that's on the same Stripe key.  Here's what Stripe sent for metadata:

      "metadata": {
        "shop_id": "XXXXXX",
        "shop_name": "My Store",
        "manual_entry": "false",
        "order_id": "c12345678909876.1",
        "email": "me@example.net"
      },

Trying to confirm with the user.  Not sure yet how to handle this.  Maybe just return a 200 if we don't find our fields?

**Comment by mikeshultz** [comment]
Yeah, these are Shopify orders coming to our webhook.

I wonder if we can even play nice here.  We could fail gracefully if we don't find our own metadata fields but it could let errors fall through the cracks without being dealt with.  This would happen with any stripe "accounts" with multiple eCommerce software on them.

Maybe we should just ask users to create a new Stripe "account"?  Looks like you have to go through and set it up again, but appears doable with Stripe.

**Comment by gullible1** [comment]
Removing the P0 label while we figure out how exactly to deal with this.
