### ISSUE TITLE
Investigate sketchy IPFS behavior when DNS first updated

### ISSUE THREAD

**Issue by nick** [OriginProtocol/dshop#30]
When I first update DNS records, IPFS can't only intermittently find content for a few minutes. Refreshing the page multiple times can result in any one of the following:

* `ipfs resolve -r /ipns/minds.ogn.app/: could not resolve name`
* `404 page not found`
* Actual content

Here's a video of me pressing refresh dozens of times. (Blank page means it served HTML correctly)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/939/82377871-8cf85e00-99e1-11ea-97e2-17de35bb433b.gif)

**Comment by mikeshultz** [comment]
Does OSX have resolve.conf?  `cat /etc/resolve.conf`

I bet your system has two DNS servers and they're not entirely in sync with each other with the TXT records.  I have not seen this(yet).

**Comment by mikeshultz** [comment]
There's been a lot of changes since this was originally reported, including a go-ipfs upgrade.  Has this been seen recently?  Still worth looking into?

**Comment by nick** [comment]
I just tested and didn't see this - will close for not until I see it again
