### ISSUE TITLE
Publish failures

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#300]
Some users are reporting publish issues in prod.
Error as reported by the user:
```
Error: Command failed: rm -rf /data/dshop-cache/mainnet/ighr/public rm: cannot remove '/data/dshop-cache/mainnet/ighr/public/ighr/sample-product/orig': Directory not empty rm: cannot remove '/data/dshop-cache/mainnet/ighr/public/ighr/sample-product/520': Directory not empty rm: cannot remove '/data/dshop-cache/mainnet/ighr/public/ighr/__tmp': Directory not empty rm: cannot remove '/data/dshop-cache/mainnet/ighr/public/dist/lightweight': Directory not empty rm: cannot remove '/data/dshop-cache/mainnet/ighr/public/images/new-shop': Directory not empty rm: cannot remove '/data/dshop-cache/mainnet/ighr/public/images/payment': Directory not empty
```

I suspect this might also be causing the "SyntaxError: unexpected token  < in JSON at position 0" reported by users as well.

**Comment by franckc** [comment]
I'm still parsing the back-end logs but I suspect the root cause is multiple deploys for the same shop running concurrently or some filesystem operation (adding a product) occurring concurrently to a deploy.
We don't have any locking in place for preventing concurrent operations on a shop.

**Comment by franckc** [comment]
My current thinking is to track pending deployment in the shop_deployments DB table or alternatively in Redis and to error out if a new deployment is attempted on a shop while a deployment is still running...

**Comment by franckc** [comment]
The failure scenarios I'm seeing from the logs are:
 - User deploys
 - IPFS cluster take several minutes to do its thing
 - In the meantime, the deploy API calls times out after 60sec
 - User retries to deploy
 - The rm -rf command fails because the IPFS deployment code from the initial deploy is creating temporary files in the directory

**Comment by mikeshultz** [comment]
Interestingly, this might be related to #308.  Some weirdness with two shops with the same name and running into `auth_token` conflicts, perhaps.  Waiting for more info from @tonyzil to help troubleshoot it.

**Comment by mikeshultz** [comment]
Also, as a suggestion, since we're taking about FS writes, why not just use a lockfile?  For example, a 0byte file at `/data/dshop-cache/mainnet/ighr/.lock`

**Comment by mikeshultz** [comment]
I think I was wrong about the auth token conflicts.  Ignore my previous message about that.

**Comment by franckc** [comment]
Yes, as an alternative we could use a sentinel file as a lock.
The DB approach is fairly simple so I don't think it over-complicates things. Also it's nice to be able to query the DB to get stats on deployment failures. Finally, in the future we may move to a non-disk based deployment (like buckets) so a file lock approach may then be more complicated?

**Comment by franckc** [comment]
Fix merged. Will test in prod.
