### ISSUE TITLE
Authentication issues when logging in

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#301]
One of our users has been having authentication issues when trying to log in to his shop. He's seeing the errors sporadically over the last 2 days - able to log in some times and other times seeing the "not authorised" error message.

**Comment by Nicholas-Leslie** [comment]
Viewed password history, there was a unnoticed change. That brings the question of password recovery...

**Comment by mikeshultz** [comment]
Agree password recovery is an important feature, but that should probably be a separate issue.  @gullible1, can we close/replace this, then?
