### ISSUE TITLE
[Printful] Error syncing Dshop with Printful 

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#302]
I managed to connect a shop with a Printful account by entering the store API key. It shows "connected" under settings > apps > Printful. However when I click on "sync", it displays the message "syncing" for a while before showing a generic error message that says "Error" (see screencap below).

<img width="1361" alt="Screenshot 2020-07-27 at 11 04 40 AM" src="https://user-images.githubusercontent.com/46481405/88499706-40408d00-cff9-11ea-8b46-aa212cc30b72.png">

**Comment by nick** [comment]
Which shop was this for?

**Comment by gullible1** [comment]
This is for ybmstore.ogn.app - I just tried syncing it and it still threw up the same error for me.
