### ISSUE TITLE
Links to shops with chinese characters/emojis in shop name don't work

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#303]
Some users have tried creating shops with Chinese characters or emojis in their shop names. The links to these stores via the super admin don't work.

**Comment by franckc** [comment]
Deployed change to restrict shop names to alphanumeric characters.

@gullible1 Going to downgrade this to a P2 and I think we should work on it as part of the localization project which is on our Q3 roadmap.

**Comment by gullible1** [comment]
@shahthepro this is related to #288  - in addition to the links to these stores via the superadmin not working, I'm not sure if there might be other issues caused by the Chinese characters.

**Comment by shahthepro** [comment]
Just deployed a fix and tested it on prod. These stores work fine now.
