### ISSUE TITLE
SendGrid Domain Authentication

### ISSUE THREAD

**Issue by Nicholas-Leslie** [OriginProtocol/dshop#305]
![dns](https://user-images.githubusercontent.com/23367732/88566786-6d5b6280-d02e-11ea-9ed2-22cd75d2346f.PNG)

 app settings have connected need authentication is there a workaround? celyn.ogn.app

**Comment by mikeshultz** [comment]
I don't think we're going to support sending E-mail from our domain from other SendGrid accounts.  If you would like to configure your own SendGrid, please configure your own custom domain.
