### ISSUE TITLE
No Deployment error when adding a custom domain 

### ISSUE THREAD

**Issue by tonyzil** [OriginProtocol/dshop#308]
im  not able to add custom domain, I'm getting "No deployments" even though i have deployed.
https://fs-autossl.ogn.app/ipfs/QmPyTseRf4GuETCokJWLswgnhErVqebR5zjhhEy2Zi6Bez/#/

**Comment by mikeshultz** [comment]
Thanks for reporting this.  Will look into it.

**Comment by mikeshultz** [comment]
I'm seeing 2 different shops with the same name.  I suspect you may be looking at the wrong shop.  You can switch between them with the selector in the upper left.  If you go to Settings -> Publish you'll be able to see if you have any deployments.

@tonyzil  Can you try and verify this?  How do you feel about deleting the second one to reduce confusion?

**Comment by tonyzil** [comment]
> I'm seeing 2 different shops with the same name.  I suspect you may be looking at the wrong shop.  You can switch between them with the selector in the upper left.  If you go to Settings -> Publish you'll be able to see if you have any deployments.
> 
I have created the second store to test the bug! I will del the 2nd ASAP

**Comment by tonyzil** [comment]
Funny enough I can't see any option to del the 2nd store! But I have renamed it to 'random' the one which I'm looking at is ighr.ong.app

**Comment by mikeshultz** [comment]
Here's what I see when I try typing in a custom domain to that custom domain modal:

![ighr_test](https://user-images.githubusercontent.com/1048089/88593214-76dbcf00-d01c-11ea-8ed2-36a00c1239f3.png)

If you're 100% sure you're on the correct shop(maybe even refresh to be sure) and that that shop has deployments, can you show me what you see with a similar screenshot?  And/or provide steps on how to reproduce the error you see?

**Comment by tonyzil** [comment]
![Screenshot_20200727-232646.png](https://user-images.githubusercontent.com/67889231/88593996-b75d3c00-d060-11ea-965c-0ea763ec071d.png) I'm currently on the correct store!

**Comment by mikeshultz** [comment]
Thanks for the screenshot, that helps.  Is that Opera mobile beta?

**Comment by mikeshultz** [comment]
Ah, okay, this is after you click "Verify".  Will look into this further and get back to you

**Comment by mikeshultz** [comment]
This should be fixed.
