### ISSUE TITLE
Upgrade our IPFS to 0.5

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#31]
We should update our IPFS to the latest version, IPFS 0.5.0.

[Update procedure](https://docs-beta.ipfs.io/recent-releases/go-ipfs-0-5/update-procedure/#use-ipfs-update)

**Comment by mikeshultz** [comment]
Documenting here for posterity.  A quick backup and restore test of the IPFS node.

## Backup

Backup the IPFS data like so...

### Get PVC details

    kubectl describe pod staging-ipfs-0

### Look for the partial disk ID

    kubectl describe pvc staging-ipfs-data-staging-ipfs-0

### Get the google version of the ID

    gcloud compute disks list | grep pvc-1dae4eb6-b018-11e8-b6a5-42010a8a00ef 

### Create snapshot of the disk

    gcloud compute disks snapshot gke-origin-dc4968bf-dy-pvc-1dae4eb6-b018-11e8-b6a5-42010a8a00ef --zone=us-west1-a --storage-location=us-west1 --snapshot-names=staging-ipfs-data-staging-ipfs-0-20200528-1 --description="Snapshot of staging IPFS data"

## Restore

### Create Volume from snapshot

    gcloud compute disks create staging-ipfs-data-stating-ipfs-restore --source-snapshot=staging-ipfs-data-staging-ipfs-0-20200528-1 --zone=us-west1-a

### Create StatefulSet using Volume

Create the Kubernetes config for the new PV and STS:

    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-ipfs-staging-restore-2020052801
    spec:
      persistentVolumeReclaimPolicy: Delete
      storageClassName: ""
      capacity:
        storage: 30Gi
      accessModes:
        - ReadWriteOnce
      gcePersistentDisk:
        pdName: staging-ipfs-data-stating-ipfs-restore
        fsType: ext4
    ---
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: "ipfs-staging-restore"
      labels:
        app: "ipfs-staging-restore"
        app.kubernetes.io/name: origin
        app.kubernetes.io/part-of: ipfs
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ipfs-staging-restore
      serviceName: ipfs-staging-restore
      template:
        metadata:
          labels:
            app: ipfs-staging-restore
        spec:
          containers:
          - name: ipfs-staging-restore
            image: "ipfs/go-ipfs:v0.4.21"
            command: ["/usr/local/bin/start_ipfs", "daemon"]
            ports:
            - containerPort: 4001
              name: swarm
            - containerPort: 5001
              name: api
            - containerPort: 8080
              name: gateway
            volumeMounts:
              - mountPath: /data/ipfs
                name: ipfs-staging-restore-data
      volumeClaimTemplates:
      - metadata:
          name: ipfs-staging-restore-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: ""
          volumeName: pv-ipfs-staging-restore-2020052801  
          resources:
            requests:
              storage: 8Gi  

### Verify

    kubectl exec -it ipfs-staging-restore-0 -c ipfs-staging-restore /usr/local/bin/ipfs pin ls | wc -l

CC @franckc

**Comment by franckc** [comment]
Nice. Thanks for capturing those steps. I added a link to these instructions to our devops playbook.
