### ISSUE TITLE
'From' and 'Support' Email addresses

### ISSUE THREAD

**Issue by shahthepro** [OriginProtocol/dshop#315]
Initially we had only `supportEmail` in the config that we used as from address as well as support email for all the emails sent out. When a seller creates a shop, the [`supportEmail` is set to `<shop-token>@ogn.app`](https://github.com/OriginProtocol/dshop/blob/master/backend/routes/shops.js#L467). 

1. If the seller doesn't update this support email and hasn't configured any email server settings, network level fallback would be used to send emails. We use AWS SES config (of ogn.app domain), so the emails would work fine in that case. However, the seller wouldn't have access to the email `shop-name@ogn.app`. 

2. If he updates the support email to something like `shopsupport@originprotocol.com` and doesn't configure email servers, the emails won't go through (since the network level credentials belong to a different domain; if it does, it'd be marked as spam/spoof emails).

If he configures the email server for domain `originprotocol.com` and set his `supportEmail` to `<something>@originprotocol.com`, it would work just fine. But I don't think many users have tried configuring their own email servers yet.

So, I had to add one more param `fromEmail` to config, that would be used as from address for all emails (with a fallback value of `no-reply@ogn.app`). But @gullible1 suggested that we should use `supportEmail` as from address for all emails. This would again introduce the above the two problems. 

Some things that we can do:
- Set `Reply-To` to `supportEmail` and `From` to `fromEmail` for all emails
- Set seller's email (from DB) as `supportEmail` (but not `fromEmail` unless the seller configures any email server)
- Pipe/Forward all emails addressed to `<shop-token>@ogn.app` to seller's email. (Unnecessary if we do the above step. But I wonder how many people have already tried to reply to these emails.)
- ??

**Comment by franckc** [comment]
I'd vote for:
1. Make it mandatory in the UI as part of a new shop creation that a merchant provides their own support email rather than defaulting to <shop>@ogn.app
2. If merchant sets up their own email server, then send all emails to the buyers with From set to the merchant's support email
3. If merchant does not set up their own email server, then send all emails to the buyers with From set to dshop@originprotocol.com and set Reply-To to the merchant's support email.

**Comment by gullible1** [comment]
+1 to what @franckc said.

I think merchants will probably have to provide 2 email addresses:

- Email #1 (Store email): We (Origin) will use this address if we need to contact merchants about their store.
- Email #2 (Customer email): Customers will see this address when merchants email them
