### ISSUE TITLE
Error on /dashboard-stats

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#318]
Seen in prod recently:

    [ERROR] dshop.app: TypeError: order.data.items is not iterable
        at orders.reduce (/app/backend/routes/shops.js:1276:58)
        at Array.reduce (<anonymous>)
        at router.get (/app/backend/routes/shops.js:1276:8)

https://sentry.io/organizations/origin-protocol/issues/1803400658/events/d32f1763fd584635bd7fc806ac9e4854/?project=5338574

**Comment by nick** [comment]
Should be fixed in [this](https://github.com/OriginProtocol/dshop/commit/7d95dbc8091188f02ca7bc16688aeac2b38ab207) commit
