### ISSUE TITLE
Missing orders

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#319]
I ran the reconciliation script in prod that checks Stripe events against the orders DB and found 4 shops with missing orders:
```
#> node validatePayments.js --type=payment --allShops

2020-07-28T17:31:04.645Z [INFO]  dshop.script: Shop Sapien id=34
2020-07-28T17:31:04.732Z [INFO]  dshop.script: Found 0 orders with encrypted hashes
2020-07-28T17:31:04.870Z [INFO]  dshop.script: No order with hash QmP1QNLM5PM6ic8fUtvBRMYgA3dcRoi9QJpqDoaS5UGb2i. Created Wed Jul 15 2020 12:07:46 GMT-0700 (Pacific Daylight Time). Amount 2050

2020-07-28T17:31:18.056Z [INFO]  dshop.script: Shop Homs House id=119
2020-07-28T17:31:18.136Z [INFO]  dshop.script: Found 0 orders with encrypted hashes
2020-07-28T17:31:18.256Z [INFO]  dshop.script: No order with hash Qmc53PXuUYAPAAZy2S72dkovDwg3CBCTqe5Sudas2m12PU. Created Sat Jul 25 2020 19:59:12 GMT-0700 (Pacific Daylight Time). Amount 1000

2020-07-28T17:31:14.341Z [INFO]  dshop.script: Shop Kay store id=74
2020-07-28T17:31:14.424Z [INFO]  dshop.script: Found 1 orders with encrypted hashes
2020-07-28T17:31:14.565Z [INFO]  dshop.script: No order with hash QmasjUJGvosKWvqARycXyLG1Wh1ikUA7y9e7RE1ut3A529. Created Fri Jul 17 2020 14:26:09 GMT-0700 (Pacific Daylight Time). Amount 200
2020-07-28T17:31:14.565Z [INFO]  dshop.script: No order with hash QmQjqTDTSGeBEzefLWi24fZ4MuwBXfL8xTsJkrMqgcRTcz. Created Fri Jul 17 2020 13:20:25 GMT-0700 (Pacific Daylight Time). Amount 200
```

I believe "Shop Kay" missing orders were due to misconfigured webhook during internal testing.

But we need to investigate missing orders from the other two shops.

**Comment by mikeshultz** [comment]
Her webhook is pointing at rinkeby:

    [ { id: 'CENSORED',
        object: 'webhook_endpoint',
        api_version: null,
        application: null,
        created: 1593201587,
        description: null,
        enabled_events: [ 'payment_intent.succeeded' ],
        livemode: false,
        metadata: {},
        status: 'enabled',
        url: 'https://rinkebyapi.ogn.app/webhook' } ]

**Comment by franckc** [comment]
I checked the stripe config for Sapiens and everything seems ok. The only minor thing is that the webhook still points to the old URL: https://dshopapi.ogn.app/webhook but that should not matter.
I'm going to dig deeper and look at the IPFS offer data and the external_payments data.

**Comment by franckc** [comment]
I looked at that Sapien order:
- I loaded up the Stripe event data and the paymentCode associated with it is SA45NHGr7my4pLvBlSXDhjxk9Lc2RWdD
- There is a corresponding row in the external_payments table so that seems to indicate the webhook call was successfull.
- But then I don't understand why the order did not get created. It should have enqueue a task in the makeOffer queue... I'm going to look at that next...

**Comment by franckc** [comment]
More data on the Sapien missing order. There was an row in the orders table associated with that payment but the data was incomplete (for ex. it was missing the encrypted_ipfs_hash and also its status_str was set to 'error'. 
```
select * from orders where shop_id=34;
 network_id |   order_id   |                   ipfs_hash                    | encrypted_ipfs_hash | created_block | updated_block | shop_id | status | currency | value | commission | buyer | affiliate | arbitrator | finalizes | notes | data | status_str | referrer | commission_pending | commission_paid |       created_at       
------------+--------------+------------------------------------------------+---------------------+---------------+---------------+---------+--------+----------+-------+------------+-------+-----------+------------+-----------+-------+------+------------+----------+--------------------+-----------------+------------------------
          1 | 1-001-2351-0 | QmTN3w6R2A2nzFzvCFDaCyMB4TPN6J6csfmw4fBXPHMZui |                     |      10465862 |      10465862 |      34 |        |          |       |            |       |           |            |           |       | {}   | error      |          |                    |                 | 2020-07-15 19:07:40+00
```
This code has change quite a bit in the last couple weeks so I attribute this to an old bug that has since now been fixed.

Next I'm going to dig into the data for the "Homs House" (shop Id 119) missing order...

**Comment by franckc** [comment]
Looked at the Homs House shopId 119 missing order. 
Here is the data:
 - Stripe event id: evt_1H9050ItNHnR3lherlKoNqOj
 - Encrypted offer hash: Qmc53PXuUYAPAAZy2S72dkovDwg3CBCTqe5Sudas2m12PU
 - paymentCode: eyHD0byfdftkbnX3f3KhUI6HlSVYtUoH

There is not entry in the external_payments table for the event id evt_1H9050ItNHnR3lherlKoNqOj.
Which indicates either a) the webhook call failed or b) the webhook was never called

I checked the stripe webhook configuration for that shop and it is pointing to https://homs-house.ogn.app/stripe/webhook
This should be https://homs-house.ogn.app/webhook.
So it would explain why we never got the webhook call.

Now, I'm not sure how the user got the webhook URL misconfigured given that we register the webhook programmatically.
I suspect the user may have edied the webhook URL manually hereafter thru their stripe.com account?
@gullible1 It would be interesting to reach out to that user and ask them what they did.

Also on my side I'll look at adding some extra validation to check the webhook URL is properly configure when the "Verify" button of the "Stripe connect" modal is clicked. Currently the "Verify" says everything is properly configured.

Lowering priority to P2 for now.

**Comment by nick** [comment]
Stripe webhooks were created with `publicUrl` instead of `backendUrl` initially, so this was probably just an old store. Webhooks need to point at https://dshop.originprotocol.com not https://*.ogn.app - the former is node and the latter is IPFS.

**Comment by franckc** [comment]
Yes, good point regarding the URL.

This is not an old store. It was created on July 22nd.

The code fallbacks to using publicURL (see [this line](https://github.com/OriginProtocol/dshop/blob/master/backend/routes/shops.js#L830)) but netConfig.backendUrl should always be set so I don't understand why the publicUrl would get used.
I'll clean up this code anyway.

Let me also check the webhook configuration for all the shops to make sure they use the proper backend URL.

**Comment by franckc** [comment]
Ran a script to check webhook configs. Here is the result:
- Found 2 stores using invalid webhook URLs:
```
[INFO]  dshop.cli: Checking Stripe config for shop 118 Eternal Word Shop
[ERROR] dshop.cli: Webhook id we_1H7lNlLtPKyKtVPOnigH3jmA points to invalid URL https://eternal-word-shop.ogn.app/
[INFO]  dshop.cli: Checking Stripe config for shop 119 Homs House
[ERROR] dshop.cli: Webhook id we_1H7YJGItNHnR3lhe8WcCHQig points to invalid URL https://homs-house.ogn.app/stripe/webhook
```
It's interesting to note those store ids are consecutive. We might have had a bug in the code for a short period of time that caused the URL to get set incorrectly.

- Found a couple of shops that don't have valid Stripe API keys:
  - shop 197 Chinar's Store
  - shop 169 Clean Breakaway
It actually looks like in admin, even though the API key is invalid, the "Connect Stripe" module shows it as "Connected". It should not. We may be missing some code to check the validity of the keys. Or maybe the UI does handle properly the fact that the key is invalid.

**Comment by franckc** [comment]
I fixed shop id 118 and 119 by manually de-registering then re-registering the webhook.

**Comment by franckc** [comment]
Marking this issue as closed.
I'll run the verification script regularly in the next few days to make sure we don't see new mis-configured webhooks.
#325 will take care of hardening the code.
