### ISSUE TITLE
Validation of stripe keys

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#325]
Do basic validation of Stripe keys in the UI and backend before saving them.  They should all have predictable prefixes.

- `pk_test_` - test publishable key
- `sk_test_` - test secret key
- `pk_live_` - production publishable key
- `sk_live_` - production secret key

**Comment by franckc** [comment]
See #319 for example of shops with incorrect configurations in prod.

**Comment by franckc** [comment]
Setting priority as P1 since I expect this will be a common mistake/source of customer support inquiries.
