### ISSUE TITLE
[Publish flow] Inform the user about DNS propagation delays

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#339]
Currently once a shop is published, we don't let the user know it will take a couple minutes for the DNS changes to propagate.
This may confuse the user:
 - for a first time publish, if they go to their website public URL, it will error out
 - for a publish to update their site, if they go to they shop's URL, the changes may not get reflected yet

We should find a way to communicate this to the user. Some options:
 a) add some text on the "Publish success" modal
 b) have a progress meter when publishing that shows at which step the publish is at, and that includes DNS update.

**Comment by franckc** [comment]
CC @gullible1

**Comment by mikeshultz** [comment]
I would prefer to close this in favor of an entirely async modular deploy process.

**Comment by gullible1** [comment]
Addressed by the new custom domains flow and closing this.
