### ISSUE TITLE
Bad log message

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#341]
Seen on prod:

    [INFO]  dshop.routes.shops: Created shop 220 with name undefined

All of them seem to say `undefined`

**Comment by franckc** [comment]
Ah yeah my bad. Let me fix... Thanks for caching this.

**Comment by franckc** [comment]
Fixed in this commit: https://github.com/OriginProtocol/dshop/commit/0f81c005f3f8de6bdcd522674f1a4027ec811424
