### ISSUE TITLE
[Analytics] Make Seller Analytics data available in the DB

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#375]
Implement P0 and P1 from  the [spec](https://docs.google.com/document/d/1KgFl-qD5y0wW-khyQJeZL7M5FWmAYL4e4X4_bsjqIEA/edit).

- [ ] Added new product(s)
- [ ] Number of products added per merchant
- [ ] Activated Stripe
- [ ] Connected web3 wallet

**Comment by franckc** [comment]
Here is what I'm thinking in terms of implementation:
- Have an "ETL" job that runs periodically (probably daily). It would go thru every active shop, extracts the data and write it into dedicated reporting tables in the prod DB.
- The data would get pulled from different sources
   - Existing DB tables. For example shops, shop_deployments, orders
   - Shop configuration stored as encrypted JSON in the DB
   - Shop data on IPFS: products, collections
   - Potentially in the future we could also pull data from other sources such as Stripe, Paypal, Printful.
- The reporting tables would get prefixed with "etl_" to clearly differentiate them vs production tables.
- The ETL job would get scheduled using the Bull framework that we already use for queues

**Comment by nick** [comment]
Sounds good to me 👍
