### ISSUE TITLE
Shop health check endpoint

### ISSUE THREAD

**Issue by nick** [OriginProtocol/dshop#379]
I'm thinking we should have a basic health check endpoint that can be polled on occasion to check:

* All API keys are functioning
* All relevant webhooks are correctly configured
* All frontend configs (eg config.json) adhere to schemas
* External payments have corresponding orders
* Other things... (please comment)

We can also show the results of the health check in the admin

**Comment by mikeshultz** [comment]
A shop diagnostics endpoint.  :+1: 

Related but probably not relevant: there's a couple of health checks for the backend itself under `/health`.

**Comment by franckc** [comment]
+1 Good idea!

**Comment by franckc** [comment]
Could other data that might be helpful:
 - any job in the makeOffer or event queue that failed and that are associated with the shop
 - deployment failures

The more tools we provide to the merchants for self-diagnosing issues, the less support work we'll have to handle.

**Comment by franckc** [comment]
Implemented in #663
