### ISSUE TITLE
stackdriver logging and montioring not working after upgrade

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#387]
Looks like logging changed with GKE 1.15.

https://cloud.google.com/stackdriver/docs/solutions/gke?_ga=2.62684972.-1096631868.1566935796

stackdriver doesn't appear to be ingesting logs now and most stackdriver-based metrics, altering, and charting are currently unavailable.

**Comment by mikeshultz** [comment]
Think I have this pretty much set but waiting for data for some to confirm they're working.

**Comment by franckc** [comment]
Well done captain! FYI, I can now see recent logs on the GCP LogsViewer
