### ISSUE TITLE
Price changes not reflected correctly

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#397]
One of our users changed the price of one of his products from $250 to $3. This change was reflected on the storefront home page, but upon clicking in to the product and also when checking out, the price displayed is still $250. See screencaps below.

I was unable to reproduce this on my store. The user's store is thepeerart.ogn.app.

![image (1)](https://user-images.githubusercontent.com/46481405/89768809-b3d0b700-db2e-11ea-8f53-39ea3da2d997.png)
![image](https://user-images.githubusercontent.com/46481405/89768844-c0550f80-db2e-11ea-8901-af7132fd7e5a.png)
![image (2)](https://user-images.githubusercontent.com/46481405/89768853-c4812d00-db2e-11ea-81e2-5d550286292f.png)

**Comment by nick** [comment]
This happens when the price of the product and the variant are different. When the user selects 'This product has multiple options', we should hide the product level pricing and SKU as they're no longer relevant. Instead, they should be derived from the variant price.

**Comment by gullible1** [comment]
Ah makes sense. Closing this as I opened #409 .
