### ISSUE TITLE
UI shows "listing is pending creation" message despite the back-end returning the listing Id

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#430]
We have a user that reported not being able to connect their wallet/create listing successfully.
They see the following message: "Your listing is pending creation using account 0xa344987A9BD5..."

I looked at the back-end data and it seems fine.
This is for shop id 842.
The shops table indicates the wallet was connected and the listing created:
 - walletAddress = 0xa344987A9BD5...
 - listingId = 1-001-2598
Etherscan shows a transaction was mined for that listing id and was submitted by that wallet address.

I was able to reproduce the by loading up that shop in the super-admin UI and going to Settings > Payments

The call to https://dshop.originprotocol.com/config does return a config with the proper wallet address and listing Id.

So it looks like somehow the UI is not displaying properly the data?

**Comment by franckc** [comment]
@nick Any idea what could be wrong with this dshop?

**Comment by franckc** [comment]
More data:
 - The back-end processed a ListingCreated event for shop 842 and it updated the DB and config.json as shown in these logs:
```
2020-08-13 13:12:07.234 PDT
[INFO] dshop.utils.handleLog: Associated shop 842 with listing Id 1-001-2598
[INFO] dshop.utils.handleLog: Shop 842: set listingId to 1-001-2598 in config at /data/dshop-cache/mainnet/solar-world/data/config.json
```

But it looks like somehow afterwards the listingId field in the config.json file was overwritten. It is now empty. Here is its content in prod:
```
#> cat /data/dshop-cache/mainnet/solar-world/data/config.json
...
  "networks": {
    "1": {
      "marketplaceContract": "0x698ff47b84837d3971118a369c570172ee7e54c2",
      "listingId": "",
...
```

**Comment by franckc** [comment]
Was able to reproduce in my local by adding a delay in the listener's method _processEventListingCreated to simulate Mainnet mining delays. Here is the scenario causing the bug:
 - user connects their wallet and sends the createListing transaction
 - sometime after that, the tx gets mined and the listener updates listingId in the DB and config.json. But the UI does not get automatically refreshed so it still thinks there is no listingId.
 - The user makes a change to a different config and saves. The UI calls PUT /shop/config with a listingId set to null.
 - The front-end set listingId to null in config.json

Not sure what's the best way to handle this.
 - I can add some checks on the back-end to prevent a null listingId from overwriting an existing one. A minor drawback is that it will prevent unsetting the listingId using the UI - but I don't think that's something that really matters.
 - That would still not solve the bad user experience of the UI not refreshing automatically when the ListingCreated tx is mined to reflect the listingID. Not sure how to address that. Currently the user has to manually refresh the page after the tx is mined to see the listingId and be able to publish... Maybe the UI should periodically poll the back-end to check if the listingId was recorded?

@nick any thoughts on the above?

**Comment by nick** [comment]
I recently updated the UI to wait for the transaction to be mined (though not on prod yet), so hopefully that helps the UI confusion.

I think we can also update the UI to not send listingId unless it's being explicitly set. The only way to do that right now is from the 'Server' tab, which is superuser only.

**Comment by franckc** [comment]
Great that the UI automatically updates when the tx is mined. I think there is still a possible race condition if the back-end for some reason is delayed in processing the event.

So agreed it's a good idea to not send the listingId unless it's been touched in the UI (might be something we should consider doing for all config fields BTW).

**Comment by gullible1** [comment]
@franckc Will #475 resolve this?

**Comment by franckc** [comment]
@gullible1 yes!

**Comment by gullible1** [comment]
legend, thanks for the hard work @franckc
