### ISSUE TITLE
Shop View link error

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#44]
Using the 'View' link on the super-admin shops page breaks super-admin session.

https://github.com/OriginProtocol/dshop/blob/90c0b859263c124c5f6df17779be49a82cc245db/shop/src/pages/super-admin/shops/Shops.js#L49-L50

This seems to have broken the loaded super-admin config and attempts to load the API from `0.0.0.0:3000`.  Not sure if this is from network being broken.  The shop config loads and appears correct, though I'm not sure why we're changing the entire super-admin session to begin with instead of just linking to the domain or IPFS hash?

Undefining `sessionStorage.dataDir` returns the session to normal.

**Comment by nick** [comment]
This should be fixed now
