### ISSUE TITLE
Buyer unable to pay with custom ERC20 token

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#472]
Reported in prod.

Shop: "pay with Dap"
Browser: Firefox
Wallet: Metamask
ERC20 address: 0x78a685e0762096ed0f98107212e98f8c35a9d1d8 (DAP)

Buyer gets error: " insufficient balance "

Buyer also tried using TrustWallet and got the same error.

**Comment by shahthepro** [comment]
Tried reproducing this locally but couldn't. Any idea on which shop it occurred? @franckc

**Comment by franckc** [comment]
@shahthepro Thanks for trying to reproduce it. It was reported on this shop: "Pay with Dap": https://pay-with-dap.ogn.app/#/

**Comment by Ourbloc** [comment]
Hello any update on this?

**Comment by Ourbloc** [comment]
@shahthepro

**Comment by Ourbloc** [comment]
![Screenshot_20200923-130109](https://user-images.githubusercontent.com/51546089/94045073-f0820600-fd9c-11ea-8c83-7e978c95b14f.png)

**Comment by Ourbloc** [comment]
This is a screenshot the issue.

**Comment by franckc** [comment]
@Ourbloc: Thanks for the screenshot.

I see you only have 0.0143 DAP in your wallet, which is a bit less than $15 at xchange rate 1 DAP = $1,045.13
How much is the item you are trying to buy? 

Also, it looks like the screenshot was from a mobile phone. Was it on Android or IOS ? And what web3 wallet are you using on your phone?

**Comment by Ourbloc** [comment]
It's $12

**Comment by Ourbloc** [comment]
> @Ourbloc: Thanks for the screenshot.
> 
> I see you only have 0.0143 DAP in your wallet, which is a bit less than $15 at xchange rate 1 DAP = $1,045.13
> How much is the item you are trying to buy?
> 
> Also, it looks like the screenshot was from a mobile phone. Was it on Android or IOS ? And what web3 wallet are you using on your phone?

i'm using trust wallet, ive also tried metamask on chrome. the quantity you see for dap is how much the item cost.

**Comment by franckc** [comment]
#780 is fixed and should fix this as well.
