### ISSUE TITLE
Setup page colors kill usability

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#476]
The colors on the initial setup page make it almost unusable.  Perhaps it's due to my system colors, but I can't tell when I've highlighted things, and the dropdowns are white on white when an option is not highlighted.

Most of the text in this input is actually highlighted:

![selected](https://user-images.githubusercontent.com/1048089/91084225-e2f42780-e608-11ea-9584-0339aa6e600e.png)

Couldn't get a screenshot of the dropdown without doing some weirdness.

**Comment by phyninja** [comment]
Hi Mike,

This appears to be fixable by increasing the contrast between form elements. Here are some mockups:

![1](https://user-images.githubusercontent.com/10854442/113289299-a52d4f00-930d-11eb-991e-023fc0052f49.png)
![2](https://user-images.githubusercontent.com/10854442/113289315-aa8a9980-930d-11eb-8562-9e3ce1a22615.png)
![3](https://user-images.githubusercontent.com/10854442/113289316-ab233000-930d-11eb-9208-488c4c710154.png)
![4](https://user-images.githubusercontent.com/10854442/113289318-abbbc680-930d-11eb-9bf1-e51ee92b466f.png)

You may see that the first two options have a "gradient" associated with them; the following two are more "solid" in nature. What looks best?

**Comment by mikeshultz** [comment]
Aure, our resident design master said he likes the last one the best.  Thanks for taking care of this.  :+1:
