### ISSUE TITLE
Create IPFS cluster

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#50]
Create a standalone IPFS cluster.

- Primarily for dshop but with pins from previous node for added redundancy
- multi-region
- probably with ipfs-cluster

### Questions

Questions I'd like to answer along the way...

- What ops/orchestration/config management to use for distributed cluster?
- will still need a gateway, with cert issuer, perhaps regional?  does let's encrypt offer cert management for multiple nodes yet?
- Dshop uses API, how will that be available now?  Can we add pins without?  ipfs-cluster ACLs?
- Consider how might "nodes" fit within this cluster?  Follower?  Can these nodes add pins to the cluster?

Ref #31

**Comment by mikeshultz** [comment]
Why closed?  This isn't complete

**Comment by gullible1** [comment]
fat fingers sorry D:

**Comment by mikeshultz** [comment]
Done.  Not multi-region but future plans on making it so.
