### ISSUE TITLE
Include quantity in CSV export

### ISSUE THREAD

**Issue by nick** [OriginProtocol/dshop#506]
Include the number of items ordered in the CSV export

**Comment by phyninja** [comment]
Hi Nick,

Attached below are screenshots of 
1) An example CSV
2) The same CSV imported into a spreadsheet program

Looking forward to your feedback.
![Screenshot 2020-11-15 at 10 40 22 AM](https://user-images.githubusercontent.com/10854442/99177675-fe675e00-2731-11eb-93c5-0df3623a77fc.png)
![Screenshot 2020-11-15 at 10 41 56 AM](https://user-images.githubusercontent.com/10854442/99177680-03c4a880-2732-11eb-972f-1847176c56d8.png)

**Comment by franckc** [comment]
Implemented in #782
