### ISSUE TITLE
Pull all mock up images for products from Printful

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#510]
I added a mug to my anna-test-16.ogn.app store and selected 3 mock up images on Printful that I wanted to use to showcase different angles of my product. 

<img width="402" alt="Screenshot 2020-08-26 at 10 42 13 AM" src="https://user-images.githubusercontent.com/46481405/91382121-93f20080-e85b-11ea-837d-9bfec814f952.png">

However, it seems like only the main mock up image is being pulled onto Dshop. We should display all the mock up images that the user selected on Printful.

<img width="658" alt="Screenshot 2020-08-27 at 11 51 44 AM" src="https://user-images.githubusercontent.com/46481405/91382187-b4ba5600-e85b-11ea-8c59-e157440b39f7.png">

**Comment by shahthepro** [comment]
Was debugging this. This doesn't look like an issue. 

- When you set up Printful for the first time, multiple mocks work fine. 
- You have to select `Force refresh images` when you are re-syncing your Printful store to get all the mocks. 

Let me know if this should be changed.

**Comment by gullible1** [comment]
Ah, let's leave it for now then, thanks @shahthepro !
