### ISSUE TITLE
Order processing failure on coinlist store

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#519]
We have an order failing processing on the coinlist store.

The failure is likely due to the following:
 1. Merchant sets up a shop with a PGP key and publishes
 1. Merchant updates their PGP key in admin, saves but does NOT publish.
 1. Buyer makes a purchase. The offer is encrypted with the published PGP key
 1. The back-end fails processing the order when it tries to decrypt the offer since it uses the new private key saved in the DB.

**Comment by franckc** [comment]
@gullible1 I think we manage the coinlist store. Do you have any recollection of updating that store's PGP key?

**Comment by franckc** [comment]
I fixed the pgp keys moving forward. The back-end had good keys. But the issue was with the pgp public key in config.json
I'm still not sure how we ended up in that state...

We are still not able to process the order that was placed while we had that invalid pgp public key.
And we don't have the contact information of the buyer.
Some more details about that order:
 - tx hash: https://etherscan.io/tx/0x211522282d00422cf5565b09fe98f7329ac1db8e5a6c8057968158f8c264e27b
 - payment was made in ETH for about $24
 - the PGP public key used for encrypting the offer data was: ```-----BEGIN PGP PUBLIC KEY BLOCK-----\r\n\r\nxjMEXnztjBYJKwYBBAHaRw8BAQdAeDjwuFdK3ZaYkpgNI68N/c7VfmzT8h6T\r\nxNMerEWbOxLNGkQtU2hvcCA8ZHNob3BAZXhhbXBsZS5jb20+wngEEBYKACAF\r\nAl587YwGCwkHCAMCBBUICgIEFgIBAAIZAQIbAwIeAQAKCRDB32/1v2KFpIkI\r\nAQCELV0DBVppjxKpWysMZ2P7Fq3PkbIfWLIEjW4NPvMfCAD/YUOJ7IV/xUzN\r\nRP4k7pVH7CgOMoXnWuo3zwk+3vMKHQ/OOARefO2MEgorBgEEAZdVAQUBAQdA\r\nkG2Hp5TtoHxAxwb9g7XozCKmAmqWgFnvMU/mPEkNZVEDAQgHwmEEGBYIAAkF\r\nAl587YwCGwwACgkQwd9v9b9ihaSSBAD/dzv1GKJkmNlk70qJkQxo8wp0GhQZ\r\nnjviGNZb7M+V38gA/01+Xy0WkPnv/c0Nudmm+eClxaYu5T42y/IGoPt8frAC\r\n=lxtj\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n```

@gullible1 @nick Would you have by any chance in your data the private key for this public key^^^ ?

If not, the only think I can think of we can do is withdraw the offer on the marketplace and send some ETH back to the buyer to cover for their gas fees when they made the offer.

**Comment by gullible1** [comment]
@franckc where should I look for the private key? I'll see if I have it.

**Comment by franckc** [comment]
We had another order that is failing for what I believe is the same reason.
tx hash: 0xa8897d59c5aed937a0f3555b92f758bd6e374bb78bd26c4e7aeba2e1d2751b56

@gullible1 To fix this moving forward, we need to re-publish the coinlist store. Is that ok to do so? If yes, please go ahead asap.

**Comment by gullible1** [comment]
@franckc re-published!

**Comment by franckc** [comment]
Sadly there is nothing we can do to process those orders on the backend.
I believe DSS mentioned he was aware of those 2 failed orders and placed them manually?
@gullible1 Do you mind double checking?

A separate issue #570 was created to track work for being able to recover configs.

Going to close this issue for now since there is no engineering work to do.
