### ISSUE TITLE
Printful product sync removes existing non-Printful products

### ISSUE THREAD

**Issue by ParzivalWins** [OriginProtocol/dshop#532]
Current Config:  
Existing inventory of non-Printful products. Added Printful App integration with API

Observed scenario: Click "Sync Printful" button.  Select Yes to confirmation.  All Printful products downloaded.  Existing Non-Printful products and collections removed. 

Expected behavior: Click "Sync Printful" button.  Select Yes to confirmation.  All Printful products downloaded.  Existing Non-Printful products and collections maintained with deccriptions. 

Workaround:  Go to HOME.  Select "Add your first product".  Add back all non-Printful products to product inventory.

**Comment by franckc** [comment]
Great issue report @ParzivalWins - very detailed. Appreciate it!

CC @gullible1 for prioritization

**Comment by ParzivalWins** [comment]
Tested. I'm sorry but I don't think removing non-synced Printful items is an expected behavior. See screenshot. @gullible1 @shahthepro  . I wouldn't want to lose the existing catalog of products with a sync.  Thank you. 
![Screen Shot 2020-09-30 at 1 26 34 PM](https://user-images.githubusercontent.com/25649258/94736341-f178e180-0320-11eb-97a1-eb602ac96840.png)

**Comment by shahthepro** [comment]
@ParzivalWins Anna wanted to just show a warning now. We are avoiding having both printful and manually-managed products in the same store to keep things simple. cc @gullible1
