### ISSUE TITLE
Wallet Issues 

### ISSUE THREAD

**Issue by Nicholas-Leslie** [OriginProtocol/dshop#533]
![reconnect](https://user-images.githubusercontent.com/23367732/92327985-7ab83380-f055-11ea-8e7e-3571e4e2e556.PNG)

Has wallet address for metamask but no shop ID? I have wasted over $25 in gas fees. This is on a second shop...

**Comment by franckc** [comment]
Hi @Nicholas-Leslie,

Thanks for the report. Sorry you ran into this issue. This is very brittle those days given how badly the ethereum network is congested...

We are actively working on making it easier to create a shop, without having to send create a listing on the marketplace smart contract. 

In the meantime, I fixed your account so you should be all good (your listingId is 1-001-2634.
