### ISSUE TITLE
Off-chain changes broke offline payment Accept

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#547]
Before the off-chain changes, if an order was made with the offline payment method, the merchant would have the option to Accept or Reject the order from the admin order details page.

This is currently broken, the payment is immediately marked as Paid after the order is placed.

Here are the payment statuses and actions we should support:
- Payment starts as "Pending", merchant sees the option to either "Accept" or "Reject" it
- If the merchant Accepts it, the order becomes "Paid". Merchant has the option to "Refund".
- If the merchant Rejects it, the order becomes "Rejected"
- If the merchant Refunds, the order becomes "Refunded"

**Comment by franckc** [comment]
@gullible1 Can you please confirm the payment status above make sense for offline payments? Thanks!

**Comment by gullible1** [comment]
@franckc yes they make sense! For shops that have integrated Printful and have enabled manual transactions, we should probably make sure that the order is only pushed to Printful after the merchant marks an order as paid.

**Comment by franckc** [comment]
Thanks @gullible1 - ah yes, great point about making sure the printful order for offline payment only gets processed once the payment gets *accepted* by the merchant. CC @shahthepro

**Comment by shahthepro** [comment]
Sure, will make that change. @franckc
