### ISSUE TITLE
Publishing a store should not require to connect a wallet 

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#548]
From Anna: "if I make changes to my new store and try to publish the changes, it still asks me to connect a wallet first, and when I click Connect the modal goes away but the changes remain unpublished, and it goes on like that in a loop for me."

**Comment by jackyq2015** [comment]
Maybe you have to pay gas in order to publish your store? Not sure. But I found sometimes the metamask doesn't popup when asking for the payment confirmation. You have to open it manually and confirm it and it will resume. At least it happened when I tired listing.

**Comment by shahthepro** [comment]
> But I found sometimes the metamask doesn't popup when asking for the payment confirmation. You have to open it manually and confirm it and it will resume.

@jackyq2015 MetaMask doesn't open a Popup if one already exists. Make sure you don't any other open MetaMask popups. Anyway, this doesn't seem related to this issue.
