### ISSUE TITLE
Tutorial to setup

### ISSUE THREAD

**Issue by jackyq2015** [OriginProtocol/dshop#550]
Is  there a tutorial to setup dshop to ipfs from backend and front end? the document in readme is not so clear. I can setup the local environment and access from browser following link:
https://github.com/OriginProtocol/dshop/blob/master/shop/README.md
But what missing is how to setup a production environment(deploy to Etherum and IPFS).

**Comment by gullible1** [comment]
Did you still need help with this @jackyq2015 ? You can chat with our engineers anytime in Origin's Dshop #engineering channel on Discord: https://discord.gg/jyxpUSe

<img width="236" alt="Screenshot 2020-09-25 at 10 48 38 AM" src="https://user-images.githubusercontent.com/46481405/94221005-d8d18b80-ff1c-11ea-9883-46229e6db319.png">
