### ISSUE TITLE
Order confirmations for Printful products show "free shipping"

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#562]
On the pundi-x.ogn.app shop, which is integrated with Printful, all of the orders that have been made are showing "free shipping". We should be using the Printful shipping API and charging the customer for shipping, so that the merchant will not have to cover shipping costs.

<img width="440" alt="Screenshot 2020-09-24 at 1 14 05 AM" src="https://user-images.githubusercontent.com/46481405/94046422-412c4a00-fe03-11ea-8134-ed75c19cca4b.png">

<img width="280" alt="Screenshot 2020-09-24 at 1 13 54 AM" src="https://user-images.githubusercontent.com/46481405/94046520-5c975500-fe03-11ea-855b-f199b7e4d6f9.png">

**Comment by franckc** [comment]
Not positive this is related but I see some errors like this in the backend logs:
```
[ERROR] dshop.app: TypeError: Cannot read property 'address1' of undefined
    at fetchShippingEstimate (/app/backend/utils/printful.js:149:27)
    at router.post (/app/backend/routes/printful.js:63:26)
```
