### ISSUE TITLE
Improve support for PayPal echeck pending payments

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#571]

**Comment by franckc** [comment]
See issue #554 

In case a buyer pays with echeck on PayPal, the payment does not clear immediately. It takes 2 to 3 days.
PayPal calls our webhook with a payment intent as "PAYMENT.CAPTURE.PENDING".
Then once the echeck clears, PayPal calls our webhook again.

It is confusing to the merchant since on their end, they receive an email from PayPal to let them know they got a pending payment but on our end they do not see the order because we don't insert an order in this case.

=> We should create an order with payment_status set to Pending.

**Comment by franckc** [comment]
CC @gullible1 for prioritization

I think this is fairly high given PayPal's penetration on the buyer side and the fact that echeck are a fairly common payment type on paypal.

**Comment by gullible1** [comment]
@franckc Agree let's prioritise this. 

- While Paypal is processing it, Dshop shows status "pending"
- Upon clicking through to the order details, the yellow toast we currently have for pending manual payments can say that payment is being processed by Paypal, and that the status will be updated once that's Paypal is done processing

<img width="920" alt="Screenshot 2020-09-25 at 11 27 24 AM" src="https://user-images.githubusercontent.com/46481405/94223268-1ab10080-ff22-11ea-8e57-e148d90832f6.png">

I think no action is required from the merchant here, unless we aren't able to update the status automatically and require the merchant to mark it as paid?

**Comment by franckc** [comment]
@gullible1 correct, there should be no manual action required from the merchant - once we get the webhook call from PayPal that the payment has cleared, we'll mark the order as Paid and auto-fulfill it in case the merchant opted-in for auto-fulfillment.

**Comment by shahthepro** [comment]
@franckc I can pick this up if you don't mind

**Comment by franckc** [comment]
@shahthepro sure! thanks a lot:)

**Comment by shahthepro** [comment]
Closing this since #581 has been merged
