### ISSUE TITLE
Adding existing user as admin on another store produces strange results

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#578]
When an existing user who had been added as an admin on another store tries to log in, this screen is shown right after logging in:

<img width="354" alt="Screenshot 2020-09-27 at 9 43 22 PM" src="https://user-images.githubusercontent.com/46481405/94366591-ded98f00-010b-11eb-8213-45486fa5becb.png">

Adding a new store at this step brings the user to the admin panel, where the other stores associated with the user shows up in the drop down on the top left, but the same "no results" page appears again after logging out and back in again.

Steps to reproduce:
1) Sign up for Dshop account as new user
2) Go to a different shop and add yourself as an admin (same email address as in step 1)
3) log in with your email address in step 1

**Comment by phyninja** [comment]
Hi @gullible1,

On my machine used for development, I'm seeing similar behavior. Stranger still is the fact that in my experience, adding a new user with a _completely different_ email address also displayed the 'No results' screen. Because this is a database issue, I will need time to troubleshoot it. Please feel free to escalate the issue if necessary.

**Comment by phyninja** [comment]
Hi again, 

I have been able to triage this as a caching problem by testing on Brave, Firefox, and Safari on Mac. The issue occurs intermittently, but the one consistent workaround is to quit and re-launch the web browser when it happens. I will proceed to close this issue in 3 business days in case there are no additional comments. 

cc @shahthepro

**Comment by phyninja** [comment]
Hi @gullible1,

I'm unaware of there being activity related to this issue, and am therefore inclined to close it. Please don't hesitate to re-open it if need be.
