### ISSUE TITLE
Payment-specific discounts

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#614]
Allow merchants to offer discounts if buyers use a specified payment method. [See on Zeplin](https://zpl.io/VKe8BdP).

- [ ] These will be applied automatically upon checkout

- [ ] These can be used in conjunction with an active discount code

- [ ] Buyers will be able to see any available payment-specific discounts under the price on the product detail page. 

- [ ] [See on Zeplin](https://zpl.io/aw8P9Dd)

**Comment by shahthepro** [comment]
Closed through #746
