### ISSUE TITLE
Receipt details page broken

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#630]
I made a purchase in prod and the receipt email I received included a link to the order details page.
When I click on it, that pages says "Loading..." but does not finish loading.

Notes:
 - I re-deployed my shop before making the purchase so it should have been running the latest code as of Friday 10/9
 - There is no error in the JS console
 - The network tab does not show any request to IPFS for fetching the order data.

This is easily reproducible by clicking on this link: https://franck-shop-a.ogn.app/#/order/QmWqKiYCNnyM9rH2xJ4m4GwkRwhz1RD8Ketcenh4vs2Yrx?auth=1qx74581slhxen4swrxy7ig1ux4yr3er

**Comment by shahthepro** [comment]
Have pushed a changeset that should fix this

**Comment by franckc** [comment]
verified the fix in prod.

note that merchant will have to re-deploy their shop in order to pick up the fix.

CC @gullible1 ^^^
