### ISSUE TITLE
Incorrect DNS instructions

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#634]
A user reported seeing this screen:

<img width="587" alt="Screen_Shot_2020-10-08_at_12 41 25_PM" src="https://user-images.githubusercontent.com/1048089/96034052-3707d500-0e1e-11eb-967d-d2e5c8a3bbf4.png">

`@` is only valid on some providers, should only be used for "root" records, and we can not instruct users to CNAME a "root" domain, or all of their records essentially get overrided by ours.  Any root domains need to be A records.  I made an explicit effort to add A record support before and clean all this up.  Is this a regression?  

Also, for a subdomain record(store.example.com) they should be instructed to create records for `store` and `_dnslink.store`, not what's displayed here.

CC @shahthepro @nick

**Comment by mikeshultz** [comment]
I changed this a bit.  The Host field now shows fqdns with a trailing dot, which I think may be more explanatory(and is starndard for SLDs (e.g. `example.com.`)).  It may be better to stick to a standard bind zone file format, which would require the subdomain names only on non-SLD records (e.g. `_dnslink.store`).  Will wait and see if there's any feedback from users.

**Comment by micahalcorn** [comment]
@mikeshultz I'm going to close this one for now.
