### ISSUE TITLE
Stripe integration/connection keeps getting lost

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#636]
The owners of the [Argent store](https://dshop.originprotocol.com/argent.ogn.app) has reported that their Stripe integration/connection keeps getting lost. It would be successfully connected and then after a while, become disconnected again. If the merchant saves, then refreshes the page, the Stripe connection disappears every time.

**Comment by franckc** [comment]
@gullible1 I think our UI is confusing. Not only they need to click "Save" on the modal, but they also need to click "Update" at the bottom of the page to persist the settings in the config... We should definitely improve the UI.

**Comment by gullible1** [comment]
@franckc They did click update and apparently the connection still gets lost upon refreshing the page. Switching between menu options within Settings doesn't cause it to disappear though.

**Comment by franckc** [comment]
@gullible1 is it reproducible on one of our test shop?

**Comment by gullible1** [comment]
I couldn't reproduce it by refreshing the page, but I did notice that when I initially logged into my test store (annas-fiestas.ogn.app), the public key was still there from the last time I had connected my Stripe but the secret key was missing @shahthepro cc @franckc

**Comment by shahthepro** [comment]
@gullible1 Couldn't reproduce this anywhere. I tried using my test keys on their shop and it worked fine too. Are you sure, they are entering the creds correctly?

**Comment by gullible1** [comment]
I've asked them to let us know if it happens again @shahthepro . Moving this to backlog while I keep an eye on this for a while.

**Comment by gullible1** [comment]
Taking out of backlog since we just managed to reproduce it @shahthepro with the config update.
