### ISSUE TITLE
Google Analytics - Not Working - Tag not installed after publishing

### ISSUE THREAD

**Issue by ParzivalWins** [OriginProtocol/dshop#638]
I have configured a GA property and tag for the website account.  I have put the TAG into the advanced section. 

"UA-......-1"

I have tested the firing of the tag and GA nor browser is receiving the JS code firing. See screenshot with Tag Assistant details. 
![Screen Shot 2020-10-15 at 6 57 18 PM](https://user-images.githubusercontent.com/25649258/96204272-c1ccfa80-0f18-11eb-8a34-27904f2878e6.png)

Thank you for your efforts.

**Comment by franckc** [comment]
Thanks for reporting this issue!

CC @gullible1 for prioritiziation

**Comment by ParzivalWins** [comment]
Tag is firing now. Confirmed.  Not sure if it was cache or build time issue. 
![Screen Shot 2020-10-19 at 11 42 57 AM](https://user-images.githubusercontent.com/25649258/96498105-7e1c0e80-1200-11eb-9327-2a63b792fc6a.png)
