### ISSUE TITLE
Prinful webhook not configured properly for some shops

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#689]
While running the config diagnostic tool on shops in production, I noticed that on some shops printful is enabled but the webhook is not configured properly. More specifically, the shop's config in the DB does not have the field ```printfulWebhookSecret``` set at all or in some cases it has an empty value.

This will cause Printful's webhook calls to get ignored. See code [here](https://github.com/OriginProtocol/dshop/blob/master/backend/routes/printful.js#L81).
I verified it is happening by checking the back-end logs for entries "Invalid secret, ignoring event" and there are quite a few.

Example of shops impacted: Brave (id 2), Pundi X Collections (id 187), Uphold (id 4).
This can be validated by running the script:
```
node configCli.js --networkId=1 --shopId=<X> --operation=getKey --key=printfulWebhookSecret
```

The user impact is two fold:
 - The buyer won't receive an "item shipped" email update
 - Syncs on the printful side won't get reflected on the dshop side

**Comment by franckc** [comment]
@shahthepro 
 - Any idea why this would be happening?
 - What's the best way to fix this for merchants? I'm thinking I can write a script to de-register the webhook, then re-register it?

**Comment by franckc** [comment]
CC @gullible1 for visibility

**Comment by shahthepro** [comment]
@franckc I'm wondering if the issue that affected Stripe with config changes has something to do with this. I guess some parts were refactored when moving code to `/logic/shop/config`. Let me check and get back on this

**Comment by franckc** [comment]
Thanks @shahthepro - yes, it could totally be me breaking something when I did that config refactor...

Looking at the [config code](https://github.com/OriginProtocol/dshop/blob/master/backend/logic/shop/config.js#L314), when a merchant de-registers their shop for printful, I wonder if we should also clear up all the other printful related config fields such as "printful" and "printfulAutoFulfill". Right now we only clear printfulWebhookSecret and that's maybe why I'm confused since my validation script assumed that if shopConfig.printful is defined, then the printful integration is enabled.

**Comment by franckc** [comment]
As a data point, I landed my refactor PR #689 on October 6th, but I see errors "Invalid secret, ignoring event" in the back-end logs starting on Sept 23rd. So I think it may not be related to those config changes...

**Comment by phyninja** [comment]
Hi all,
I'm trying to understand this issue a little better; it sounds like the shops mentioned above [Brave, Pundi X Collections, Uphold] may have de-registered themselves on printful, but because some additional printful-related fields still exist (for these shops), @franckc's validation script is detecting that printful is still enabled for them. 

Please correct me if I'm wrong.

**Comment by franckc** [comment]
@phyninja Thanks for your interest in our project! :) This issue might be a bit hard to tackle since having access to the back-end data makes it easier to troubleshoot what's going on. But if you are looking for issues you could help with, look at the ones labeled "good first issue": https://github.com/OriginProtocol/dshop/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by franckc** [comment]
Haven't done it yet but I plan on:
  - writing a script to de-register then un-register those shops
  - send out a PR that set the config fields "printful" and "printfulAutoFulfill" to null in the logic that handles de-registration

**Comment by franckc** [comment]
Done.
