### ISSUE TITLE
New themes not loading properly for Safari users

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#692]
Multiple reports of our new themes not loading properly on Safari. See below for screenshots for the ybmstore.ogn.app shop and also the Galleria theme.

![ybmsafari](https://user-images.githubusercontent.com/46481405/97127814-9dbdb480-1775-11eb-8b40-fa7290c34180.png)

<img width="1278" alt="maxsafari" src="https://user-images.githubusercontent.com/46481405/97127809-97c7d380-1775-11eb-84c3-dc95cc93c729.png">

**Comment by nick** [comment]
Should be fixed now
