### ISSUE TITLE
Piecemeal deployment settings

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#716]
Will probably be useful to be able to customize deployment options for a node/network.  A rough early matrix with potentially other providers added/supported as we go:

               | Files  | DNS | CDN | E-mail |
    -----------+--------+-----+-----+--------+
    Cloudflare | u      | s   | s   | n      |
    AWS        | s      | s   | s   | s      |
    GCP        | o      | o   | o   | s      |
    SendGrid   | n      | n   | n   | s      |
    Pinata     | o      | n   | n   | n      |
    IPFS Clust | o      | n   | n   | n      |
    -----------+--------+-----+-----+--------|

    o = used by Origin node
    u = unsupported
    s = supported
    n = not applicable

For our use case, it may be best to use GCP as bucket and DNS and use another provider for CDN(e.g. AWS).  The majority of users will probably just use a single provider, but there's bound to be some that don't.  Right now we're making inferences according to configured credentials which may be confusing not match up to what node operators expect.

This *probably* doesn't need to be encrypted, but may be simpler to add to the encrypted network config.

**Comment by mikeshultz** [comment]
Coming up with a kind of deployment definition to describe what deployment options there are, what config each needs, and which components each depends on.  First draft:

https://gist.github.com/mikeshultz/2c433bdcf48e1130e3d8309b3f5f3532

From here, we can derive some kind of serializable config for each network(or maybe per shop in the future) for what deployment options are enabled.  This would also be used to inform the UI of what config and dependencies are needed.

It's a start on making deployment choices explicit and unsurprising.

**Comment by mikeshultz** [comment]
Network config could include a simple "key equals enabled" array.  For instance our backend config could look like this: 

    ["ipfs-pinata", "gcp-files", "gcp-dns", "gcp-cdn", "sendgrid"]

**Comment by micahalcorn** [comment]
@mikeshultz shall we move this one to the backlog?

**Comment by mikeshultz** [comment]
Done, actually
