### ISSUE TITLE
Orders with negative amount flowing thru the system

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#723]
See shop 'Injective Protocol'. For example order 1-001-81-1258-VMBE8BL6

I think there are 2 issues:
1. we let users use a discount even if it is no longer avail
2. the discount causes the total amount to go negative

**Comment by gullible1** [comment]
I think we should add an additional step in the discount code creation flow for minimum requirements, where the user can set one of the following requirements:
- no minimum requirements (they're willing to absorb the losses)
- minimum purchase amount
- (maybe) minimum quantity of items purchased

**Comment by franckc** [comment]
Data point:
 - when sent a negative amount, Stripe charges a flat fee of 50cents on the buyer's credit card.
 - there are 9 orders on the Injective shop that have negative amounts.

**Comment by franckc** [comment]
Closing this for now. It is still happening (rarely), but that's for shops that haven't published to pick up the bug fix.
