### ISSUE TITLE
Paypal not displayed as "connected" even though it is

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#727]
On the argent.ogn.app shop, Paypal doesn't show as connected even though the user has connected it and clicked "update".

<img width="705" alt="Screenshot 2020-10-30 at 11 35 58 PM" src="https://user-images.githubusercontent.com/46481405/97725496-33a46700-1b09-11eb-8c26-de432174066b.png">

When the "connect" button is clicked again, the modal shows the saved credentials. Paypal also appears as an option during checkout.

<img width="842" alt="Screenshot 2020-10-30 at 11 36 03 PM" src="https://user-images.githubusercontent.com/46481405/97725572-4ae35480-1b09-11eb-95f4-81a53396d667.png">

**Comment by mikeshultz** [comment]
Possibly related, I've been seeing lots of these in the logs:

    [DEBUG] dshop.utils.paypal: Failed to validate paypal creds HttpError: {"error":"invalid_client","error_description":"Client Authentication failed"}
        at IncomingMessage.<anonymous> (/app/node_modules/@paypal/paypalhttp/lib/paypalhttp/http_client.js:136:22)
        at IncomingMessage.emit (events.js:327:22)
        at IncomingMessage.EventEmitter.emit (domain.js:548:15)
        at endReadableNT (_stream_readable.js:1327:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21) {
      statusCode: 401,
      headers: {
        'content-type': 'application/json',
        'content-length': '77',
        connection: 'close',
        date: 'Fri, 30 Oct 2020 16:13:41 GMT',
        'cache-control': 'max-age=0, no-cache, no-store, must-revalidate',
        'paypal-debug-id': 'b30e23f83198e',
        'x-paypal-token-service': 'IAAS',
        'strict-transport-security': 'max-age=31536000; includeSubDomains'
      },
      _originalError: {
        text: '{"error":"invalid_client","error_description":"Client Authentication failed"}',
        statusCode: 401,
        headers: {
          'content-type': 'application/json',
          'content-length': '77',
          connection: 'close',
          date: 'Fri, 30 Oct 2020 16:13:41 GMT',
          'cache-control': 'max-age=0, no-cache, no-store, must-revalidate',
          'paypal-debug-id': 'b30e23f83198e',
          'x-paypal-token-service': 'IAAS',
          'strict-transport-security': 'max-age=31536000; includeSubDomains'
        }
      }
    }

**Comment by shahthepro** [comment]
Everything looks fine to me in that commit
