### ISSUE TITLE
Shop PayPal misconfiguration: missing paypalWebhookId

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#776]
I found an example of a shop in prod where PayPal was misconfigured. The config had the following:
 - paypalClientId and paypalClientSecret were correctly set
 - paypalWebhookId was empty.
Somehow during a config update, the paypalWebhookId got wiped.

The config history demonstrates that:
```node configCli.js --networkId=1 --shopId=1056 --logId=2314 --operation=log```
notice that paypalWebhookId = is empty but paypalClientId and paypalClientSecret are still there

```node configCli.js --networkId=1 --shopId=1056 --logId=2313 --operation=log```
notice that paypalWebhookId, paypalClientId and paypalClientSecret are all properly set

Looking at the config update code, I think the way this could happen is when the webhook registration fails, the error is not surfaced to the config. See https://github.com/OriginProtocol/dshop/blob/master/backend/utils/paypal.js#L131 

So my theory is that:
  1. User connects paypal correctly
  2. User clicks again on connect. This cause the registration code to run again, but the webhook fails to be created because it already exists (PayPal returns https://developer.paypal.com/docs/api/webhooks/v1/#error-WEBHOOK_URL_ALREADY_EXISTS). But the config still gets save, with paypalClientId and paypalClientSecret but missing paypalWebhookId

We should prevent the user from connecting again on the UI and as a double precaution on the back-end, if PayPal is already registered, we should deregister first before re-registering.

**Comment by franckc** [comment]
CC @shahthepro to validate that my theory makes sense to him as well

**Comment by shahthepro** [comment]
We actually deregister if `paypalWebhookId` exists already though: https://github.com/OriginProtocol/dshop/blob/master/backend/logic/shop/config.js#L343

**Comment by shahthepro** [comment]
Okay, it seems like `paypal` key is no longer stored in the config, that could be reason why it skipped deregistering on the reconnect. 

Removing `existingConfig.paypal` from that check should fix it.

**Comment by shahthepro** [comment]
Have pushed a commit that should fix it. We can try deploying that

**Comment by franckc** [comment]
Ah yes, fix makes sense. Ty boss!
I'll check to make sure there is no other shop in prod impacted by this issue.

**Comment by franckc** [comment]
I verified in prod that all shops that have paypal enabled are correctly configured by running:
```node configCli.js --networkId=1 --operation=checkPayPal -a```
