### ISSUE TITLE
Some swag store orders not showing up in admin

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#78]
2 Korean user orders #1-001-81-221 and #1-001-81-222 are not showing up in our swag store admin panel, despite the transactions going through successfully on their end.

**Comment by franckc** [comment]
Those 2 orders are now showing in the dshop admin but note that the user may not have received a confirmation email so it would be good to send them an email with their order id.

CC @milachoi

**Comment by franckc** [comment]
Also note that order 1-001-81-221 also now shows correctly in admin. @milachoi had reported that one not working as well.
