### ISSUE TITLE
Token decimal support

### ISSUE THREAD

**Issue by nick** [OriginProtocol/dshop#780]
The USDC token does not use 18 decimals, which the checkout currently assumes when checking balances. This results in an 'insufficient balance' error shown to the user.

**Comment by franckc** [comment]
As reported by Max, this also impact the TrustToken (TRU) since it has 8 decimals. 
See https://etherscan.io/address/0x4c19596f5aaff459fa38b0f7ed92f11ae6543784#readProxyContract

**Comment by kayyoo23** [comment]
Thanks team. 👍  Let me know when our target ETA is and I will let TrustToken team know. They are ready to launch their Dshop whenever this issue is fixed.
