### ISSUE TITLE
Disable OUSD for now

### ISSUE THREAD

**Issue by nick** [OriginProtocol/dshop#789]

**Comment by micahalcorn** [comment]
@shahthepro did this end up happening? Should we re-enable it now that OUSD is back?

**Comment by shahthepro** [comment]
I don't remember if we ever made this change. Let me check and get back

**Comment by micahalcorn** [comment]
I'd say reenable it if it's not much work. Either way, let's close this after we confirm the status.

**Comment by shahthepro** [comment]
@micahalcorn Just checked the code, my bad, I didn't disable that.

**Comment by micahalcorn** [comment]
No problem, let's just leave it in place, thanks.
