### ISSUE TITLE
Incorrect data rendering when deleting a product variant.

### ISSUE THREAD

**Issue by baaae** [OriginProtocol/dshop#794]
When deleting a product variant the table does not remove the deleted variant data. Instead it overflows into the next column and thereby displaying it incorrectly. Here's a demo, pay close attention to the SKU column.

![tamal2](https://user-images.githubusercontent.com/8410896/99998146-74e00d80-2d7b-11eb-88fe-662f4ea3b33a.gif)

**Comment by phyninja** [comment]
Hi @baaae, 
Thanks for reporting this issue. I'm attempting to fix this bug, but I'm not sure how long it will take. Please consider refreshing the webpage after clicking 'Save' as a, hopefully temporary, workaround.

**Comment by phyninja** [comment]
Hi @baaae,
A fix for this issue has been written, but is awaiting a final review from one of DShop's lead developers. I'm expecting to hear back from them by the end of next week (01/08). If you have any questions/concerns, please don't hesitate to reach out. 

Sincerely,
Rajath

**Comment by phyninja** [comment]
The change is still pending a final review. Sorry for the inconvenience!
