### ISSUE TITLE
TRU balance shown as insufficient despite sufficient funds

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#795]
Reported by Kay: "TRU (TrustToken) payment doesn't seem to work where Dshop isn't recognizing a customer's TRU balance in metamask ('Insufficient Balance' error when there's sufficient balance). I was able to replicate this using our Origin swag store. TRU address: 0x4c19596f5aaff459fa38b0f7ed92f11ae6543784"

**Comment by franckc** [comment]
This is a duplicate of #780
