### ISSUE TITLE
Oasis shop failed processing a crypto payment

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#798]
See Sentry event: https://sentry.io/organizations/origin-protocol/issues/2062990964/?environment=prod&project=5338574&referrer=alert_email

Root cause is that the back-end is trying to load the config from https://oasis-lab.ogn.app/ but the shop was published to https://oasis.ogn.app/. This issue is similar to #518

**Comment by franckc** [comment]
CC @gullible1

**Comment by franckc** [comment]
I fixed the oasis lab shop's config and processed the order. It now shows in the Oasis shop. I think Oasis now has to place the order via Printful.

Now, while looking at that I noticed a couple of other important misconfigurations for this shop:
1. They are using a *test* stripe API key. They should use a live key otherwise their customers won't be able to place an order using a credit card
2. They are still using Origin's wallet for receiving crypto payments. They should use their own.

@gullible1 @kayyoo23 Would you be able to follow up with them on 1) and 2) above? Thank you :)

**Comment by gullible1** [comment]
Will send them another email today, thanks @franckc !

**Comment by micahalcorn** [comment]
@gullible1 shall we move this to the backlog or close it?

**Comment by gullible1** [comment]
@micahalcorn closing it for now. They are resetting up their store so we can open a new issue if they run into any problems.
