### ISSUE TITLE
Brave shop: Some stripe events have no order

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#799]
Output of the Diagnostic tool:
```
"errors": [
      "Event evt_1HiSLKJ9gNNkxV4X4wwsORIm with paymentCode ecmZ4fLRprc5PLBdlzF9bswHGXXmYbm1 has no associated order",
      "Event evt_1HiRcBJ9gNNkxV4XDQkFQt4P with paymentCode S471k2HiyE1T3Tp3cnQQbh0xuAKUbT61 has no associated order",
      "Event evt_1HiQ4uJ9gNNkxV4XlkbFhdZi with paymentCode z9J3erULfWcjt7iPM0lZHFVO6tgSoqoz has no associated order"
    ]
```

**Comment by franckc** [comment]
CC @gullible1 in case any Brave customer complains about an issue with their order...

**Comment by gullible1** [comment]
Thanks @franckc ! Will keep an eye out for support requests..

**Comment by franckc** [comment]
The orders are there. It was an edge case in the diagnose tool which cause it to misreport missing orders. This [commit](https://github.com/OriginProtocol/dshop/commit/aeaf4a2ac1996ea8d74a55c307caffc9b65a898b) should fix.
