### ISSUE TITLE
Uphold payment option not available on new shop

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#824]
Newly created shops do not seem to have the option to enable Uphold payment under Settings > Payments
Only Stripe and PayPal are available.

This is a regression.

**Comment by franckc** [comment]
CC @gullible1 for prioritization

**Comment by marceloch2** [comment]
Hi @franckc just navigating to the "good first issue" tasks to find one for me to start. Probably already solved but after finishing my local environment and creating my first shop I could see and set up my uphold sandbox payment options.

<img width="1677" alt="Screenshot 2021-04-07 at 00 54 16" src="https://user-images.githubusercontent.com/1720844/113788040-7adbf700-973c-11eb-96a3-69817b6edeec.png">

**Comment by franckc** [comment]
@marceloch2 Thanks for testing it! :) Yes you are right, it looks like this got fixed... I'll close it for now.
