### ISSUE TITLE
Code deployment causes a short (~2min) back-end downtime

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/dshop#83]
This is because we are attaching to the api server container a persistent disk for the store file cache. Such a disk can only be mounted on 1 container at a time and it prevents us from doing a rolling restart when deploying a new version of the container.

Possible options to consider:
 - Use GCP filestore (e.g. NAS): https://cloud.google.com/filestore
 - Use GCP Cloud bucket or AWS S3

**Comment by franckc** [comment]
CC @mikeshultz and @nick since we discussed this on discord today.

**Comment by mikeshultz** [comment]
In an ideal world, Filestore/NFS would work like a dream but I've spent hundreds of hours troubleshooting NFS v3/v4 on Linux and FreeBSD that the thought of it gives me flashbacks.  Perhaps Google's offering is better; perhaps v4 has improved in the last few years; perhaps this low-demand use case could actually work.

A bucket storage strategy could work like this: 

1) temporary local edit in `DSHOP_CACHE`
2) User "saves" at the end of their session.  This "save" could upload to S3/GCP CloudStorage or IPFS.
3) User comes back later to edit and it's loaded from the above
4) User deploys to IPFS

Would need some sticky sessions on the balancer.

I'll take a look at this a bit more when I have more time.  There does seem to be some Kubernetes pv support for GlusterFS that I'd look into.  Might provide the use case of a network file share without NFS.

**Comment by nick** [comment]
FWIW I have had a terrible experience with GlusterFS in the past. The mention of it also gives me flashbacks.

**Comment by franckc** [comment]
Matt/Anna mentioned a future requirements that is relevant to this discussion:
 - Allow a seller to save new products created as "drafts".
 - The scenario is a seller may want to load up a bunch of products in preparation for some kind of collection launch in the near future.

**Comment by mikeshultz** [comment]
@nick Are you just mocking me, or have you actually had a bad experience with GlusterFS?  GlusterFS was actually what I was looking to replace an unreliable NFS shared storage system with on an old bare iron cluster I was running.  Heard good things about it until this one flippant message.

**Comment by nick** [comment]
Definitely not mocking you. My last job involved running a Kubernetes cluster to power a multi-tenant 'app store' of sorts such that each client could spin up and down apps that needed persistent storage. I started with GlusterFS but ended up with NFS after a lot of pain. That was years ago, though... perhaps now it's ok.

**Comment by mikeshultz** [comment]
Ref #185 #170 
PR #159 #193 #200 https://github.com/OriginProtocol/origin/pull/4486

This is now working on Rinkeby/staging.  Filestore/NFS was the simplest to setup and most native out of all the options so I just just went with that.  If it turns into cancer, we'll deal with it then.  This should be zero downtime during a backend deployment and should be massively scalable.

- [x] Persistant volume for DSHOP_CACHE moved to GCP Filestore (as a kubernetes PV)
- [x] Redis moved out of a sidecar container and a new cluster has been brought up
- [x] Listener made to be multi-instance friendly and now uses a bull queue for processing events
- [x] Kubernetes probes added to backend container to prevent pods being added to the service balancer before they're ready

IaC changes still need to be cleaned up and eventually applied to mainnet/prod as well.  I'd like to give this a couple of days and some tests to bake before moving on that.

**Comment by mikeshultz** [comment]
Fixed with https://github.com/OriginProtocol/dshop/issues/170
