### ISSUE TITLE
State Abbreviations

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/dshop#857]
I recommend using abbreviations for the state values in the shipping address form. Currently, autocompletion does not work for this field in Chrome.

<img width="377" alt="Screen Shot 2020-12-27 at 10 51 49 AM" src="https://user-images.githubusercontent.com/273937/103177718-a001c500-4831-11eb-9017-ff615b86d975.png">

**Comment by phyninja** [comment]
Hi there,

I'm sorry about any inconvenience caused by this issue. Requesting input from @shahthepro or @nick on #936.
