### ISSUE TITLE
Printful + NFT support

### ISSUE THREAD

**Issue by nick** [OriginProtocol/dshop#881]
In order to support NFTs on Printful stores, we'll need to:

* Allow non-Printful items to be added to Printful stores
* Allow inventory to be tracked on non-Printful items
* Allow an NFT contract address and list of available token IDs to be added on the product edit page
* Allow customers to specify a receiving wallet when NFT items are present in the checkout (on the payment page)
* Initiate an NFT transfer upon customer checkout

**Comment by micahalcorn** [comment]
@nick initiating the transfer is going to be a manual step for now, correct?

**Comment by nick** [comment]
We can start with a manual transfer to make things easier, yea

**Comment by ZaHuPro** [comment]
> Allow non-Printful items to be added to Printful stores

Should I create the items on printfull using API?

> Allow inventory to be tracked on non-Printful items

I guess it is already allowed

> Allow an NFT contract address and list of available token IDs to be added on the product edit page

Where should I save the contract address and token IDs? In the product's data.json file? 

> Initiate an NFT transfer upon customer checkout

Is this a contract call? Where can I find a sample NFT contract code?

**Comment by nick** [comment]
> Should I create the items on printfull using API?
Right now a store is either Printful or Non-Printful. There's no way to add a non-Printful product (eg if I wanted to list cupcakes for sale) to my existing store that has Printful products. We want non-Printful products to be ignored by any Printful related functions... eg when an order is made with both Printful and non-Printful items (eg 1 t-shirt and 1 cupcake), the calls to Printful ignore the cupcake.

> Allow inventory to be tracked on non-Printful items
Right now inventory is all or nothing. We want inventory to be tracked for the cupcake, but not the t-shirts and other Printful items

> Where should I save the contract address and token IDs? In the product's data.json file?

Perhaps lets revisit the NFT stuff after the above has been done. We'll probably just process NFT orders manually initially.

**Comment by ZaHuPro** [comment]
> Right now inventory is all or nothing. We want inventory to be tracked for the cupcake, but not the t-shirts and other Printful items

I am adding printfull products also to the inventory 
https://github.com/OriginProtocol/dshop/pull/870
