### ISSUE TITLE
Purchase not showing up on "Orders" page

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#912]
A purchase was made on the shop https://graphics-illustrations-crypto-shop.ogn.app/ but the orders page still shows "no orders yet".

For reference, the tx is: https://etherscan.io/tx/0xf944dfae1fc83e97a46939c0900285091cabcb93766ad40a11c1938de7e9930a

**Comment by franckc** [comment]
Re-ran the failed job and the order is now showing up in the graphics-illustration store.

Added more resiliency to our back-end in #913 so that this does not occur again.
