### ISSUE TITLE
Digital Downloads

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/dshop#937]
At least one prospective seller has requested the ability to sell digital downloads. I imagine this would basically be a decentralized Gumroad.

**Comment by f4rrest** [comment]
I second the request. Ideally, the backend would hit a seller's webservice to provision licenses.

**Comment by phyninja** [comment]
Could someone name one or two changes that may help us make this request a reality?

**Comment by phyninja** [comment]
@micahalcorn @f4rrest 
I will close this 'issue' since there has been little activity here. Please don't hesitate to re-open it with additional comments.

Sincerely,
Rajath
