### ISSUE TITLE
External deployer: shop settings / appearance tab

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#98]
When the user clicks "settings" in the sidebar, they will see the "appearance" tab first (the other tab is for payments settings).

[See on Zeplin](https://zpl.io/boQjl6M)

Here, they will be able to do the following:

- [x] edit their store title
- [x] add a custom domain
- [x] upload a store logo
- [x] upload a favicon
- [ ] edit their "About" page
- [x] edit their byline
- [x] add social media links ([via a dropdown on this modal](https://zpl.io/awoE1rg))

**Comment by rembrandtreyes** [comment]
I believe most of this has been completed. Are there any other states I am missing from the Zeplin link?
